/**
 * @file ShaderStrings.hpp
 * @brief Auto-generated shader strings - DO NOT EDIT.
 */

#pragma once

#include <string>
#include <unordered_map>

namespace ShaderStrings {

// Source: bvhBuilder/bound.comp
inline constexpr const char* BVHBUILDER_BOUND_COMP =
    "/**\n"
    " * @file bound.comp\n"
    " * @brief Compute shader for calculating the axis-aligned bounding box (AABB) of a scene.\n"
    " */\n"
    "\n"
    "#version 450\n"
    "\n"
    "layout(local_size_x = 128) in;\n"
    "\n"
    "/**\n"
    " * @brief Uniform buffer containing global information for BVH construction.\n"
    " */\n"
    "layout(binding = 0) uniform BvhGlobal {\n"
    "    uint nElements; // Total number of elements\n"
    "} u_bvhGlobal; // BVH global information buffer\n"
    "\n"
    "/**\n"
    " * @brief Struct representing a model instance in the scene.\n"
    " */\n"
    "struct ModelRef {\n"
    "    uint idxBlasRoot; // Index of the root node of the BLAS tree for this model\n"
    "    uint padding[3]; // Padding for alignment\n"
    "    vec4 aabbMin; // Minimum corner of the axis-aligned bounding box (AABB) for the instance\n"
    "    vec4 aabbMax; // Maximum corner of the axis-aligned bounding box (AABB) for the instance\n"
    "    mat4 xform; // Transformation matrix for this instance\n"
    "    mat4 invXform; // Inverse transformation matrix for this instance\n"
    "};\n"
    "/**\n"
    " * @brief Storage buffer for storing the model instances in the scene.\n"
    " */\n"
    "layout(binding = 1) buffer ModelRefs {\n"
    "    ModelRef modelRefs[]; // Array of model references\n"
    "} b_modelRefs; // Model references buffer\n"
    "\n"
    "/**\n"
    " * @brief Struct representing a node in the BVH tree.\n"
    " */\n"
    "struct BvhNode {\n"
    "    int idxLeft; // Index of the left child node\n"
    "    int idxRight; // Index of the right child node\n"
    "    int idxParent; // Index of the parent node\n"
    "    int idxElement; // Index of the element for leaf nodes\n"
    "\n"
    "    vec4 aabbMin; // Minimum corner of the axis-aligned bounding box (AABB) for the node\n"
    "    vec4 aabbMax; // Maximum corner of the axis-aligned bounding box (AABB) for the node\n"
    "};\n"
    "/**\n"
    " * @brief Storage buffer for storing the BVH nodes of the trees for all models.\n"
    " */\n"
    "layout(binding = 2) readonly buffer BLASs {\n"
    "    BvhNode nodes[]; // Array of BVH nodes representing the internal structure of the BVH trees\n"
    "} b_BLASs; // BLAS nodes buffer\n"
    "\n"
    "/**\n"
    " * @brief Storage buffer for storing the global minimum and maximum bounds of the scene.\n"
    " */\n"
    "layout(binding = 3) buffer BoundsUINT {\n"
    "    uvec4 minBound; // Minimum bound of the AABB (stored as ordered uints)\n"
    "    uvec4 maxBound; // Maximum bound of the AABB (stored as ordered uints)\n"
    "} b_boundsUINT; // Bounds buffer\n"
    "\n"
    "shared vec3 s_minBound[gl_WorkGroupSize.x]; // Shared array for storing local minimum bounds\n"
    "shared vec3 s_maxBound[gl_WorkGroupSize.x]; // Shared array for storing local maximum bounds\n"
    "\n"
    "const float INFINITY = 1e20; // Large value representing infinity\n"
    "\n"
    "/**\n"
    " * @brief Converts a float to an ordered uint for atomic operations. This ensures that the ordering\n"
    " *        of the floats is preserved when using atomicMin and atomicMax.\n"
    " * @param v The float value to convert.\n"
    " * @return The ordered uint representation of the float.\n"
    " */\n"
    "uint floatToOrderedUint(float v) {\n"
    "    uint x = floatBitsToUint(v);\n"
    "    return (x & 0x80000000u) != 0 ? ~x : x | 0x80000000u;\n"
    "}\n"
    "\n"
    "void main() {\n"
    "    uint gid = gl_GlobalInvocationID.x;\n"
    "    uint lid = gl_LocalInvocationID.x;\n"
    "\n"
    "    /* Each thread computes the local AABB for its assigned element */\n"
    "\n"
    "    vec3 localMin = vec3(INFINITY);\n"
    "    vec3 localMax = vec3(-INFINITY);\n"
    "    if (gid < u_bvhGlobal.nElements) {\n"
    "        ModelRef ref = b_modelRefs.modelRefs[gid];\n"
    "        BvhNode node = b_BLASs.nodes[ref.idxBlasRoot];\n"
    "\n"
    "        vec3 bmin = node.aabbMin.xyz;\n"
    "        vec3 bmax = node.aabbMax.xyz;\n"
    "\n"
    "        vec3 center = (bmin + bmax) * 0.5;\n"
    "        vec3 extent = (bmax - bmin) * 0.5;\n"
    "\n"
    "        vec3 worldCenter = (ref.xform * vec4(center, 1.0)).xyz;\n"
    "\n"
    "        mat3 m = mat3(ref.xform);\n"
    "        mat3 absM = mat3(abs(m[0]), abs(m[1]), abs(m[2]));\n"
    "\n"
    "        vec3 worldExtent = absM * extent;\n"
    "\n"
    "        localMin = worldCenter - worldExtent;\n"
    "        localMax = worldCenter + worldExtent;\n"
    "\n"
    "        b_modelRefs.modelRefs[gid].aabbMin = vec4(localMin, 0.0);\n"
    "        b_modelRefs.modelRefs[gid].aabbMax = vec4(localMax, 0.0);\n"
    "    }\n"
    "    s_minBound[lid] = localMin;\n"
    "    s_maxBound[lid] = localMax;\n"
    "\n"
    "    barrier();\n"
    "\n"
    "    /* Perform a parallel reduction to find the minimum and maximum bounds for the block */\n"
    "    for (uint stride = gl_WorkGroupSize.x / 2; stride > 0; stride >>= 1) {\n"
    "        if (lid < stride) {\n"
    "            s_minBound[lid] = min(s_minBound[lid], s_minBound[lid + stride]);\n"
    "            s_maxBound[lid] = max(s_maxBound[lid], s_maxBound[lid + stride]);\n"
    "        }\n"
    "        barrier();\n"
    "    }\n"
    "\n"
    "    /* The first thread in the block updates the global bounds using atomic operations */\n"
    "    if (lid == 0) {\n"
    "        vec3 globalMin = s_minBound[0];\n"
    "        vec3 globalMax = s_maxBound[0];\n"
    "\n"
    "        atomicMin(b_boundsUINT.minBound.x, floatToOrderedUint(globalMin.x));\n"
    "        atomicMin(b_boundsUINT.minBound.y, floatToOrderedUint(globalMin.y));\n"
    "        atomicMin(b_boundsUINT.minBound.z, floatToOrderedUint(globalMin.z));\n"
    "\n"
    "        atomicMax(b_boundsUINT.maxBound.x, floatToOrderedUint(globalMax.x));\n"
    "        atomicMax(b_boundsUINT.maxBound.y, floatToOrderedUint(globalMax.y));\n"
    "        atomicMax(b_boundsUINT.maxBound.z, floatToOrderedUint(globalMax.z));\n"
    "    }\n"
    "}\n"
    "";

// Source: bvhBuilder/bvhAABB.comp
inline constexpr const char* BVHBUILDER_BVHAABB_COMP =
    "/**\n"
    " * @file bvhAABB.comp\n"
    " * @brief Compute shader for calculating the axis-aligned bounding boxes (AABBs) of BVH nodes.\n"
    " */\n"
    "\n"
    "#version 450\n"
    "\n"
    "layout(local_size_x = 256) in;\n"
    "\n"
    "/**\n"
    " * @brief Uniform buffer containing global information for BVH construction.\n"
    " */\n"
    "layout(binding = 0) uniform BvhGlobal {\n"
    "    uint nElements; // Total number of elements\n"
    "} u_bvhGlobal; // BVH global information buffer\n"
    "\n"
    "/**\n"
    " * @brief Storage buffer for counting the number of visits to each node.\n"
    " */\n"
    "layout(binding = 12) buffer NodeVisits {\n"
    "    int visits[]; // Array of visit counts for each node\n"
    "} b_nodeVisits; // Node visit counts buffer\n"
    "\n"
    "/**\n"
    " * @brief Struct representing a node in the BVH tree.\n"
    " */\n"
    "struct BvhNode {\n"
    "    int idxLeft; // Index of the left child node\n"
    "    int idxRight; // Index of the right child node\n"
    "    int idxParent; // Index of the parent node\n"
    "    int idxTriangle; // Index of the triangle for leaf nodes\n"
    "\n"
    "    vec4 aabbMin; // Minimum corner of the axis-aligned bounding box (AABB) for the node\n"
    "    vec4 aabbMax; // Maximum corner of the axis-aligned bounding box (AABB) for the node\n"
    "};\n"
    "/**\n"
    " * @brief Storage buffer for storing the BVH nodes of the tree.\n"
    " */\n"
    "layout(binding = 13) buffer BvhNodes {\n"
    "    BvhNode nodes[]; // Array of BVH nodes representing the internal structure of the BVH tree\n"
    "} b_bvhNodes; // BVH nodes buffer\n"
    "\n"
    "void main() {\n"
    "    uint gid = gl_GlobalInvocationID.x;\n"
    "    uint N = u_bvhGlobal.nElements;\n"
    "\n"
    "    if (gid >= N)\n"
    "        return;\n"
    "\n"
    "    int node = int(gid) + int(N - 1);\n"
    "\n"
    "    while (true) {\n"
    "        int parent = b_bvhNodes.nodes[node].idxParent;\n"
    "        if (parent == -1)\n"
    "            break;\n"
    "\n"
    "        // Atomically increment the visit count for the parent node\n"
    "        // and check if it's the first visit\n"
    "        int old = atomicAdd(b_nodeVisits.visits[parent], 1);\n"
    "        if (old == 0)\n"
    "            break;\n"
    "\n"
    "        int left  = b_bvhNodes.nodes[parent].idxLeft;\n"
    "        int right = b_bvhNodes.nodes[parent].idxRight;\n"
    "\n"
    "        vec4 minL = b_bvhNodes.nodes[left].aabbMin;\n"
    "        vec4 maxL = b_bvhNodes.nodes[left].aabbMax;\n"
    "\n"
    "        vec4 minR = b_bvhNodes.nodes[right].aabbMin;\n"
    "        vec4 maxR = b_bvhNodes.nodes[right].aabbMax;\n"
    "\n"
    "        vec4 newMin = min(minL, minR);\n"
    "        vec4 newMax = max(maxL, maxR);\n"
    "\n"
    "        b_bvhNodes.nodes[parent].aabbMin = newMin;\n"
    "        b_bvhNodes.nodes[parent].aabbMax = newMax;\n"
    "\n"
    "        memoryBarrierBuffer();\n"
    "\n"
    "        node = parent;\n"
    "    }\n"
    "}\n"
    "";

// Source: bvhBuilder/bvhInternal.comp
inline constexpr const char* BVHBUILDER_BVHINTERNAL_COMP =
    "/**\n"
    " * @file bvhInternal.comp\n"
    " * @brief Compute shader for constructing the internal nodes of a BVH tree using Morton codes.\n"
    " */\n"
    "\n"
    "#version 450\n"
    "\n"
    "layout(local_size_x = 256) in;\n"
    "\n"
    "/**\n"
    " * @brief Uniform buffer containing global information for BVH construction.\n"
    " */\n"
    "layout(binding = 0) uniform BvhGlobal {\n"
    "    uint nElements; // Total number of elements\n"
    "} u_bvhGlobal; // BVH global information buffer\n"
    "\n"
    "/**\n"
    " * @brief Storage buffer for storing the input Morton codes for each triangle.\n"
    " */\n"
    "layout(binding = 8) readonly buffer MortonsIn {\n"
    "    uint codes[]; // Array of Morton codes corresponding to the triangle indices\n"
    "} b_mortonsIn; // Morton codes input buffer\n"
    "\n"
    "/**\n"
    " * @brief Struct representing a node in the BVH tree.\n"
    " */\n"
    "struct BvhNode {\n"
    "    int idxLeft; // Index of the left child node\n"
    "    int idxRight; // Index of the right child node\n"
    "    int idxParent; // Index of the parent node\n"
    "    int idxElement; // Index of the element for leaf nodes\n"
    "\n"
    "    vec4 aabbMin; // Minimum corner of the axis-aligned bounding box (AABB) for the node\n"
    "    vec4 aabbMax; // Maximum corner of the axis-aligned bounding box (AABB) for the node\n"
    "};\n"
    "/**\n"
    " * @brief Storage buffer for storing the BVH nodes of the tree.\n"
    " */\n"
    "layout(binding = 13) buffer BvhNodes {\n"
    "    BvhNode nodes[]; // Array of BVH nodes representing the internal structure of the BVH tree\n"
    "} b_bvhNodes; // BVH nodes buffer\n"
    "\n"
    "/**\n"
    " * @brief Function to compute the longest common prefix (LCP) between two Morton codes.\n"
    " * @param i Index of the first Morton code.\n"
    " * @param j Index of the second Morton code.\n"
    " * @param N Total number of triangles (size of the Morton codes array).\n"
    " * @return Length of the longest common prefix between two Morton codes, or -1 if invalid indices.\n"
    " */\n"
    "int lcp(int i, int j, uint N) {\n"
    "    if (i == j)\n"
    "        return 32;\n"
    "    if (j < 0 || j >= int(N))\n"
    "        return -1;\n"
    "\n"
    "    uint a = b_mortonsIn.codes[i];\n"
    "    uint b = b_mortonsIn.codes[j];\n"
    "    uint diff = a ^ b;\n"
    "\n"
    "    if (diff != 0)\n"
    "        return 31 - int(findMSB(diff));\n"
    "    uint idxDiff = uint(i ^ j);\n"
    "    return 32 + (31 - int(findMSB(idxDiff)));\n"
    "}\n"
    "\n"
    "void main() {\n"
    "    int i = int(gl_GlobalInvocationID.x);\n"
    "    int N = int(u_bvhGlobal.nElements);\n"
    "\n"
    "    if (i == 0)\n"
    "        b_bvhNodes.nodes[0].idxParent = -1;\n"
    "\n"
    "    if (i >= N - 1)\n"
    "        return;\n"
    "\n"
    "    // ----------------------------------\n"
    "    // Step 1: determine direction\n"
    "    // ----------------------------------\n"
    "\n"
    "    int lcpL = lcp(i, i - 1, N);\n"
    "    int lcpR = lcp(i, i + 1, N);\n"
    "\n"
    "    int d = (lcpR > lcpL) ? 1 : -1;\n"
    "\n"
    "    int deltaMin = min(lcpL, lcpR);\n"
    "\n"
    "    // ----------------------------------\n"
    "    // Step 2: find range (exponential + binary search)\n"
    "    // ----------------------------------\n"
    "\n"
    "    int lmax = 2;\n"
    "    while (lcp(i, i + lmax * d, N) > deltaMin)\n"
    "        lmax *= 2;\n"
    "\n"
    "    int l = 0;\n"
    "    for (int t = lmax / 2; t > 0; t /= 2) {\n"
    "        if (lcp(i, i + (l + t) * d, N) > deltaMin)\n"
    "            l += t;\n"
    "    }\n"
    "\n"
    "    int j = i + l * d;\n"
    "\n"
    "    int first = min(i, j);\n"
    "    int last  = max(i, j);\n"
    "\n"
    "    // ----------------------------------\n"
    "    // Step 3: find split\n"
    "    // ----------------------------------\n"
    "\n"
    "    int deltaNode = lcp(first, last, N);\n"
    "\n"
    "    int split = first;\n"
    "    int stride = last - first;\n"
    "\n"
    "    do {\n"
    "        stride = (stride + 1) >> 1;\n"
    "        int mid = split + stride;\n"
    "        if (mid < last) {\n"
    "            if (lcp(first, mid, N) > deltaNode)\n"
    "                split = mid;\n"
    "        }\n"
    "    } while (stride > 1);\n"
    "\n"
    "    // ----------------------------------\n"
    "    // Step 4: assign children\n"
    "    // ----------------------------------\n"
    "\n"
    "    int leftChild = 0, rightChild = 0;\n"
    "\n"
    "    if (split == first)\n"
    "        leftChild = split + (N - 1); // leaf\n"
    "    else\n"
    "        leftChild = split;\n"
    "\n"
    "    if (split + 1 == last)\n"
    "        rightChild = split + 1 + (N - 1); // leaf\n"
    "    else\n"
    "        rightChild = split + 1;\n"
    "\n"
    "    // write node\n"
    "    b_bvhNodes.nodes[i].idxLeft = leftChild;\n"
    "    b_bvhNodes.nodes[i].idxRight = rightChild;\n"
    "    b_bvhNodes.nodes[i].idxElement = -1; // internal node\n"
    "\n"
    "    // set parent\n"
    "    b_bvhNodes.nodes[leftChild].idxParent = i;\n"
    "    b_bvhNodes.nodes[rightChild].idxParent = i;\n"
    "}\n"
    "";

// Source: bvhBuilder/bvhLeafBLAS.comp
inline constexpr const char* BVHBUILDER_BVHLEAFBLAS_COMP =
    "/**\n"
    " * @file bvhLeafBLAS.comp\n"
    " * @brief Compute shader for constructing the leaf nodes of a BVH tree.\n"
    " */\n"
    "\n"
    "#version 450\n"
    "\n"
    "layout(local_size_x = 256) in;\n"
    "\n"
    "/**\n"
    " * @brief Uniform buffer containing global information for BVH construction.\n"
    " */\n"
    "layout(binding = 0) uniform BvhGlobal {\n"
    "    uint nElements; // Total number of elements\n"
    "} u_bvhGlobal; // BVH global information buffer\n"
    "\n"
    "/**\n"
    " * @brief Struct representing a vertex in the mesh.\n"
    " */\n"
    "struct Vertex {\n"
    "    vec4 pos; // Position\n"
    "    vec4 normal; // Normal\n"
    "    vec4 tangent; // Tangent\n"
    "    vec2 texCoord; // Texture Coordinate\n"
    "    vec2 padding; // Padding for alignment\n"
    "};\n"
    "/**\n"
    " * @brief Storage buffer containing the vertices of the mesh.\n"
    " */\n"
    "layout(binding = 1) readonly buffer Vertices {\n"
    "    Vertex vertices[]; // Array of vertices\n"
    "} b_vertices; // Vertex buffer\n"
    "\n"
    "/**\n"
    " * @brief Struct representing a triangle in the mesh.\n"
    " */\n"
    "struct Triangle {\n"
    "    uint v0; // Index of vertex 0\n"
    "    uint v1; // Index of vertex 1\n"
    "    uint v2; // Index of vertex 2\n"
    "    uint idxMaterial; // Index of the material\n"
    "};\n"
    "/**\n"
    " * @brief Storage buffer containing the triangles of the mesh.\n"
    " */\n"
    "layout(binding = 2) readonly buffer Triangles {\n"
    "    Triangle triangles[]; // Array of triangles\n"
    "} b_triangles; // Triangle buffer\n"
    "\n"
    "/**\n"
    " * @brief Storage buffer for storing the input elements indices.\n"
    " */\n"
    "layout(binding = 7) readonly buffer IndicesIn {\n"
    "    uint indices[]; // Array of elements indices\n"
    "} b_indicesIn; // Elements indices input buffer\n"
    "\n"
    "/**\n"
    " * @brief Struct representing a node in the BVH tree.\n"
    " */\n"
    "struct BvhNode {\n"
    "    int idxLeft; // Index of the left child node\n"
    "    int idxRight; // Index of the right child node\n"
    "    int idxParent; // Index of the parent node\n"
    "    int idxTriangle; // Index of the triangle for leaf nodes\n"
    "\n"
    "    vec4 aabbMin; // Minimum corner of the axis-aligned bounding box (AABB) for the node\n"
    "    vec4 aabbMax; // Maximum corner of the axis-aligned bounding box (AABB) for the node\n"
    "};\n"
    "/**\n"
    " * @brief Storage buffer for storing the BVH nodes of the tree.\n"
    " */\n"
    "layout(binding = 13) buffer BvhNodes {\n"
    "    BvhNode nodes[]; // Array of BVH nodes representing the internal structure of the BVH tree\n"
    "} b_bvhNodes; // BVH nodes buffer\n"
    "\n"
    "void main() {\n"
    "    uint i = gl_GlobalInvocationID.x;\n"
    "    uint N = u_bvhGlobal.nElements;\n"
    "\n"
    "    if (i >= N)\n"
    "        return;\n"
    "\n"
    "    uint idx = b_indicesIn.indices[i];\n"
    "    Triangle tri = b_triangles.triangles[idx];\n"
    "\n"
    "    vec3 v0 = b_vertices.vertices[tri.v0].pos.xyz;\n"
    "    vec3 v1 = b_vertices.vertices[tri.v1].pos.xyz;\n"
    "    vec3 v2 = b_vertices.vertices[tri.v2].pos.xyz;\n"
    "\n"
    "    vec3 bmin = min(v0, min(v1, v2));\n"
    "    vec3 bmax = max(v0, max(v1, v2));\n"
    "\n"
    "    uint leafIdx = i + (N - 1);\n"
    "\n"
    "    b_bvhNodes.nodes[leafIdx].idxLeft = -1;\n"
    "    b_bvhNodes.nodes[leafIdx].idxRight = -1;\n"
    "    b_bvhNodes.nodes[leafIdx].idxTriangle = int(idx);\n"
    "\n"
    "    b_bvhNodes.nodes[leafIdx].aabbMin = vec4(bmin, 0.0);\n"
    "    b_bvhNodes.nodes[leafIdx].aabbMax = vec4(bmax, 0.0);\n"
    "}\n"
    "";

// Source: bvhBuilder/bvhLeafTLAS.comp
inline constexpr const char* BVHBUILDER_BVHLEAFTLAS_COMP =
    "/**\n"
    " * @file mortonTLAS.comp\n"
    " * @brief Compute shader for calculating Morton codes for model instances.\n"
    " */\n"
    "\n"
    "#version 450\n"
    "\n"
    "layout(local_size_x = 128) in;\n"
    "\n"
    "/**\n"
    " * @brief Uniform buffer containing global information for BVH construction.\n"
    " */\n"
    "layout(binding = 0) uniform BvhGlobal {\n"
    "    uint nElements; // Total number of elements\n"
    "} u_bvhGlobal; // BVH global information buffer\n"
    "\n"
    "/**\n"
    " * @brief Struct representing a model instance in the scene.\n"
    " */\n"
    "struct ModelRef {\n"
    "    uint idxBlasRoot; // Index of the root node of the BLAS tree for this model\n"
    "    uint padding[3]; // Padding for alignment\n"
    "    vec4 aabbMin; // Minimum corner of the axis-aligned bounding box (AABB) for the instance\n"
    "    vec4 aabbMax; // Maximum corner of the axis-aligned bounding box (AABB) for the instance\n"
    "    mat4 xform; // Transformation matrix for this instance\n"
    "    mat4 invXform; // Inverse transformation matrix for this instance\n"
    "};\n"
    "/**\n"
    " * @brief Storage buffer for storing the model instances in the scene.\n"
    " */\n"
    "layout(binding = 1) buffer ModelRefs {\n"
    "    ModelRef modelRefs[]; // Array of model references\n"
    "} b_modelRefs; // Model references buffer\n"
    "\n"
    "/**\n"
    " * @brief Storage buffer for storing the computed axis-aligned bounding box (AABB) of the scene.\n"
    " */\n"
    "layout(binding = 3) readonly buffer BoundsUINT {\n"
    "    uvec4 minBound; // Minimum bound of the AABB (stored as ordered uints)\n"
    "    uvec4 maxBound; // Maximum bound of the AABB (stored as ordered uints)\n"
    "} b_boundsUINT; // Bounds buffer\n"
    "\n"
    "/**\n"
    " * @brief Storage buffer for storing the output element indices after computing Morton codes.\n"
    " */\n"
    "layout(binding = 5) writeonly buffer Indices {\n"
    "    uint indices[]; // Array of element indices corresponding to the Morton codes\n"
    "} b_indices; // Element indices buffer\n"
    "/**\n"
    " * @brief Storage buffer for storing the computed Morton codes for each triangle.\n"
    " */\n"
    "layout(binding = 6) writeonly buffer Mortons {\n"
    "    uint codes[]; // Array of Morton codes corresponding to the triangle indices\n"
    "} b_mortons; // Morton codes buffer\n"
    "\n"
    "const float EPS = 0.00001; // Small epsilon value\n"
    "\n"
    "/**\n"
    " * @brief Converts an ordered unsigned integer back to a floating-point value.\n"
    " *\n"
    " * This function takes an ordered unsigned integer, which is used for atomic operations in the\n"
    " * bounding box computation, and converts it back to a floating-point value. The conversion\n"
    " * accounts for the ordering of the bits to ensure that the resulting float is correctly\n"
    " * reconstructed.\n"
    " *\n"
    " * @param v The ordered unsigned integer to be converted.\n"
    " * @return The corresponding floating-point value.\n"
    " */\n"
    "float orderedUintToFloat(uint v) {\n"
    "    return (v & 0x80000000u) != 0u ? uintBitsToFloat(v & 0x7FFFFFFFu) : uintBitsToFloat(~v);\n"
    "}\n"
    "\n"
    "/**\n"
    " * @brief Expands a 10-bit integer into a 30-bit integer by inserting two zeros between each bit.\n"
    " *\n"
    " * This function takes a 10-bit integer and expands it to a 30-bit integer by interleaving zeros\n"
    " * between the bits. This is used for computing Morton codes for spatial indexing.\n"
    " *\n"
    " * @param v The input 10-bit integer to be expanded.\n"
    " * @return The expanded 30-bit integer with interleaved zeros.\n"
    " */\n"
    "uint expandBits(uint v) {\n"
    "    v = (v * 0x00010001u) & 0xFF0000FFu;\n"
    "    v = (v * 0x00000101u) & 0x0F00F00Fu;\n"
    "    v = (v * 0x00000011u) & 0xC30C30C3u;\n"
    "    v = (v * 0x00000005u) & 0x49249249u;\n"
    "    return v;\n"
    "}\n"
    "\n"
    "/**\n"
    " * @brief Computes the 30-bit Morton code for a 3D point normalized to the unit cube.\n"
    " *\n"
    " * This function takes a 3D point with coordinates in the range [0, 1] and computes its Morton code\n"
    " * by expanding each coordinate into a 10-bit integer and interleaving the bits. The resulting\n"
    " * Morton code is a 30-bit integer that can be used for spatial indexing.\n"
    " *\n"
    " * @param v The input 3D point with coordinates in the range [0, 1].\n"
    " * @return The computed 30-bit Morton code for the input point.\n"
    " */\n"
    "uint morton3D(vec3 v) {\n"
    "    v = clamp(v * 1024.0, 0.0, 1023.0);\n"
    "\n"
    "    uint xx = expandBits(uint(v.x));\n"
    "    uint yy = expandBits(uint(v.y));\n"
    "    uint zz = expandBits(uint(v.z));\n"
    "\n"
    "    return (xx << 2) | (yy << 1) | zz;\n"
    "}\n"
    "\n"
    "void main() {\n"
    "    uint gid = gl_GlobalInvocationID.x;\n"
    "    if (gid >= u_bvhGlobal.nElements)\n"
    "        return;\n"
    "\n"
    "    ModelRef ref = b_modelRefs.modelRefs[gid];\n"
    "    vec3 bmin = ref.aabbMin.xyz;\n"
    "    vec3 bmax = ref.aabbMax.xyz;\n"
    "\n"
    "    vec3 minBound = vec3(\n"
    "        orderedUintToFloat(b_boundsUINT.minBound.x),\n"
    "        orderedUintToFloat(b_boundsUINT.minBound.y),\n"
    "        orderedUintToFloat(b_boundsUINT.minBound.z)\n"
    "    );\n"
    "    vec3 maxBound = vec3(\n"
    "        orderedUintToFloat(b_boundsUINT.maxBound.x),\n"
    "        orderedUintToFloat(b_boundsUINT.maxBound.y),\n"
    "        orderedUintToFloat(b_boundsUINT.maxBound.z)\n"
    "    );\n"
    "\n"
    "    vec3 extent = maxBound - minBound;\n"
    "    extent = max(extent, vec3(EPS)); // Avoid division by zero\n"
    "    vec3 center = (bmin + bmax) * 0.5;\n"
    "    vec3 norm = (center - minBound) / extent;\n"
    "\n"
    "    uint morton = morton3D(norm);\n"
    "\n"
    "    b_indices.indices[gid] = gid;\n"
    "    b_mortons.codes[gid] = morton;\n"
    "}\n"
    "";

// Source: bvhBuilder/mortonBLAS.comp
inline constexpr const char* BVHBUILDER_MORTONBLAS_COMP =
    "/**\n"
    " * @file mortonBLAS.comp\n"
    " * @brief Compute shader for calculating Morton codes for triangles in a model.\n"
    " */\n"
    "\n"
    "#version 450\n"
    "\n"
    "layout(local_size_x = 128) in;\n"
    "\n"
    "/**\n"
    " * @brief Uniform buffer containing global information for BVH construction.\n"
    " */\n"
    "layout(binding = 0) uniform BvhGlobal {\n"
    "    uint nElements; // Total number of elements\n"
    "} u_bvhGlobal; // BVH global information buffer\n"
    "\n"
    "/**\n"
    " * @brief Struct representing a vertex in the mesh.\n"
    " */\n"
    "struct Vertex {\n"
    "    vec4 pos; // Position\n"
    "    vec4 normal; // Normal\n"
    "    vec4 tangent; // Tangent\n"
    "    vec2 texCoord; // Texture Coordinate\n"
    "    vec2 padding; // Padding for alignment\n"
    "};\n"
    "/**\n"
    " * @brief Storage buffer containing the vertices of the mesh.\n"
    " */\n"
    "layout(binding = 1) readonly buffer Vertices {\n"
    "    Vertex vertices[]; // Array of vertices\n"
    "} b_vertices; // Vertex buffer\n"
    "\n"
    "/**\n"
    " * @brief Struct representing a triangle in the mesh.\n"
    " */\n"
    "struct Triangle {\n"
    "    uint v0; // Index of vertex 0\n"
    "    uint v1; // Index of vertex 1\n"
    "    uint v2; // Index of vertex 2\n"
    "    uint idxMaterial; // Index of the material\n"
    "};\n"
    "/**\n"
    " * @brief Storage buffer containing the triangles of the mesh.\n"
    " */\n"
    "layout(binding = 2) readonly buffer Triangles {\n"
    "    Triangle triangles[]; // Array of triangles\n"
    "} b_triangles; // Triangle buffer\n"
    "\n"
    "/**\n"
    " * @brief Uniform buffer for storing the axis-aligned bounding box (AABB) of the model.\n"
    " */\n"
    "layout(binding = 3) readonly buffer Bounds {\n"
    "    vec4 minBound; // Minimum bound of the AABB\n"
    "    vec4 maxBound; // Maximum bound of the AABB\n"
    "} u_bounds; // Bounds buffer\n"
    "\n"
    "/**\n"
    " * @brief Storage buffer for storing the output element indices after computing Morton codes.\n"
    " */\n"
    "layout(binding = 5) writeonly buffer Indices {\n"
    "    uint indices[]; // Array of element indices corresponding to the Morton codes\n"
    "} b_indices; // Element indices buffer\n"
    "/**\n"
    " * @brief Storage buffer for storing the computed Morton codes for each triangle.\n"
    " */\n"
    "layout(binding = 6) writeonly buffer Mortons {\n"
    "    uint codes[]; // Array of Morton codes corresponding to the triangle indices\n"
    "} b_mortons; // Morton codes buffer\n"
    "\n"
    "const float EPS = 0.00001; // Small epsilon value\n"
    "\n"
    "/**\n"
    " * @brief Expands a 10-bit integer into a 30-bit integer by inserting two zeros between each bit.\n"
    " *\n"
    " * This function takes a 10-bit integer and expands it to a 30-bit integer by interleaving zeros\n"
    " * between the bits. This is used for computing Morton codes for spatial indexing.\n"
    " *\n"
    " * @param v The input 10-bit integer to be expanded.\n"
    " * @return The expanded 30-bit integer with interleaved zeros.\n"
    " */\n"
    "uint expandBits(uint v) {\n"
    "    v = (v * 0x00010001u) & 0xFF0000FFu;\n"
    "    v = (v * 0x00000101u) & 0x0F00F00Fu;\n"
    "    v = (v * 0x00000011u) & 0xC30C30C3u;\n"
    "    v = (v * 0x00000005u) & 0x49249249u;\n"
    "    return v;\n"
    "}\n"
    "\n"
    "/**\n"
    " * @brief Computes the 30-bit Morton code for a 3D point normalized to the unit cube.\n"
    " *\n"
    " * This function takes a 3D point with coordinates in the range [0, 1] and computes its Morton code\n"
    " * by expanding each coordinate into a 10-bit integer and interleaving the bits. The resulting\n"
    " * Morton code is a 30-bit integer that can be used for spatial indexing.\n"
    " *\n"
    " * @param v The input 3D point with coordinates in the range [0, 1].\n"
    " * @return The computed 30-bit Morton code for the input point.\n"
    " */\n"
    "uint morton3D(vec3 v) {\n"
    "    v = clamp(v * 1024.0, 0.0, 1023.0);\n"
    "\n"
    "    uint xx = expandBits(uint(v.x));\n"
    "    uint yy = expandBits(uint(v.y));\n"
    "    uint zz = expandBits(uint(v.z));\n"
    "\n"
    "    return (xx << 2) | (yy << 1) | zz;\n"
    "}\n"
    "\n"
    "void main() {\n"
    "    uint gid = gl_GlobalInvocationID.x;\n"
    "    if (gid >= u_bvhGlobal.nElements)\n"
    "        return;\n"
    "\n"
    "    Triangle tri = b_triangles.triangles[gid];\n"
    "\n"
    "    vec3 v0 = b_vertices.vertices[tri.v0].pos.xyz;\n"
    "    vec3 v1 = b_vertices.vertices[tri.v1].pos.xyz;\n"
    "    vec3 v2 = b_vertices.vertices[tri.v2].pos.xyz;\n"
    "\n"
    "    vec3 minBound = u_bounds.minBound.xyz;\n"
    "    vec3 maxBound = u_bounds.maxBound.xyz;\n"
    "\n"
    "    vec3 extent = maxBound - minBound;\n"
    "    extent = max(extent, vec3(EPS)); // Avoid division by zero\n"
    "    vec3 center = (v0 + v1 + v2) * (1.0 / 3.0);\n"
    "    vec3 norm = (center - minBound) / extent;\n"
    "\n"
    "    uint morton = morton3D(norm);\n"
    "\n"
    "    b_indices.indices[gid] = gid;\n"
    "    b_mortons.codes[gid] = morton;\n"
    "}\n"
    "";

// Source: bvhBuilder/mortonTLAS.comp
inline constexpr const char* BVHBUILDER_MORTONTLAS_COMP =
    "/**\n"
    " * @file mortonTLAS.comp\n"
    " * @brief Compute shader for calculating Morton codes for model instances.\n"
    " */\n"
    "\n"
    "#version 450\n"
    "\n"
    "layout(local_size_x = 128) in;\n"
    "\n"
    "/**\n"
    " * @brief Uniform buffer containing global information for BVH construction.\n"
    " */\n"
    "layout(binding = 0) uniform BvhGlobal {\n"
    "    uint nElements; // Total number of elements\n"
    "} u_bvhGlobal; // BVH global information buffer\n"
    "\n"
    "/**\n"
    " * @brief Struct representing a model instance in the scene.\n"
    " */\n"
    "struct ModelRef {\n"
    "    uint idxBlasRoot; // Index of the root node of the BLAS tree for this model\n"
    "    uint padding[3]; // Padding for alignment\n"
    "    vec4 aabbMin; // Minimum corner of the axis-aligned bounding box (AABB) for the instance\n"
    "    vec4 aabbMax; // Maximum corner of the axis-aligned bounding box (AABB) for the instance\n"
    "    mat4 xform; // Transformation matrix for this instance\n"
    "    mat4 invXform; // Inverse transformation matrix for this instance\n"
    "};\n"
    "/**\n"
    " * @brief Storage buffer for storing the model instances in the scene.\n"
    " */\n"
    "layout(binding = 1) buffer ModelRefs {\n"
    "    ModelRef modelRefs[]; // Array of model references\n"
    "} b_modelRefs; // Model references buffer\n"
    "\n"
    "/**\n"
    " * @brief Storage buffer for storing the computed axis-aligned bounding box (AABB) of the scene.\n"
    " */\n"
    "layout(binding = 3) readonly buffer BoundsUINT {\n"
    "    uvec4 minBound; // Minimum bound of the AABB (stored as ordered uints)\n"
    "    uvec4 maxBound; // Maximum bound of the AABB (stored as ordered uints)\n"
    "} b_boundsUINT; // Bounds buffer\n"
    "\n"
    "/**\n"
    " * @brief Storage buffer for storing the output element indices after computing Morton codes.\n"
    " */\n"
    "layout(binding = 5) writeonly buffer Indices {\n"
    "    uint indices[]; // Array of element indices corresponding to the Morton codes\n"
    "} b_indices; // Element indices buffer\n"
    "/**\n"
    " * @brief Storage buffer for storing the computed Morton codes for each triangle.\n"
    " */\n"
    "layout(binding = 6) writeonly buffer Mortons {\n"
    "    uint codes[]; // Array of Morton codes corresponding to the triangle indices\n"
    "} b_mortons; // Morton codes buffer\n"
    "\n"
    "const float EPS = 0.00001; // Small epsilon value\n"
    "\n"
    "/**\n"
    " * @brief Converts an ordered unsigned integer back to a floating-point value.\n"
    " *\n"
    " * This function takes an ordered unsigned integer, which is used for atomic operations in the\n"
    " * bounding box computation, and converts it back to a floating-point value. The conversion\n"
    " * accounts for the ordering of the bits to ensure that the resulting float is correctly\n"
    " * reconstructed.\n"
    " *\n"
    " * @param v The ordered unsigned integer to be converted.\n"
    " * @return The corresponding floating-point value.\n"
    " */\n"
    "float orderedUintToFloat(uint v) {\n"
    "    return (v & 0x80000000u) != 0u ? uintBitsToFloat(v & 0x7FFFFFFFu) : uintBitsToFloat(~v);\n"
    "}\n"
    "\n"
    "/**\n"
    " * @brief Expands a 10-bit integer into a 30-bit integer by inserting two zeros between each bit.\n"
    " *\n"
    " * This function takes a 10-bit integer and expands it to a 30-bit integer by interleaving zeros\n"
    " * between the bits. This is used for computing Morton codes for spatial indexing.\n"
    " *\n"
    " * @param v The input 10-bit integer to be expanded.\n"
    " * @return The expanded 30-bit integer with interleaved zeros.\n"
    " */\n"
    "uint expandBits(uint v) {\n"
    "    v = (v * 0x00010001u) & 0xFF0000FFu;\n"
    "    v = (v * 0x00000101u) & 0x0F00F00Fu;\n"
    "    v = (v * 0x00000011u) & 0xC30C30C3u;\n"
    "    v = (v * 0x00000005u) & 0x49249249u;\n"
    "    return v;\n"
    "}\n"
    "\n"
    "/**\n"
    " * @brief Computes the 30-bit Morton code for a 3D point normalized to the unit cube.\n"
    " *\n"
    " * This function takes a 3D point with coordinates in the range [0, 1] and computes its Morton code\n"
    " * by expanding each coordinate into a 10-bit integer and interleaving the bits. The resulting\n"
    " * Morton code is a 30-bit integer that can be used for spatial indexing.\n"
    " *\n"
    " * @param v The input 3D point with coordinates in the range [0, 1].\n"
    " * @return The computed 30-bit Morton code for the input point.\n"
    " */\n"
    "uint morton3D(vec3 v) {\n"
    "    v = clamp(v * 1024.0, 0.0, 1023.0);\n"
    "\n"
    "    uint xx = expandBits(uint(v.x));\n"
    "    uint yy = expandBits(uint(v.y));\n"
    "    uint zz = expandBits(uint(v.z));\n"
    "\n"
    "    return (xx << 2) | (yy << 1) | zz;\n"
    "}\n"
    "\n"
    "void main() {\n"
    "    uint gid = gl_GlobalInvocationID.x;\n"
    "    if (gid >= u_bvhGlobal.nElements)\n"
    "        return;\n"
    "\n"
    "    ModelRef ref = b_modelRefs.modelRefs[gid];\n"
    "    vec3 bmin = ref.aabbMin.xyz;\n"
    "    vec3 bmax = ref.aabbMax.xyz;\n"
    "\n"
    "    vec3 minBound = vec3(\n"
    "        orderedUintToFloat(b_boundsUINT.minBound.x),\n"
    "        orderedUintToFloat(b_boundsUINT.minBound.y),\n"
    "        orderedUintToFloat(b_boundsUINT.minBound.z)\n"
    "    );\n"
    "    vec3 maxBound = vec3(\n"
    "        orderedUintToFloat(b_boundsUINT.maxBound.x),\n"
    "        orderedUintToFloat(b_boundsUINT.maxBound.y),\n"
    "        orderedUintToFloat(b_boundsUINT.maxBound.z)\n"
    "    );\n"
    "\n"
    "    vec3 extent = maxBound - minBound;\n"
    "    extent = max(extent, vec3(EPS)); // Avoid division by zero\n"
    "    vec3 center = (bmin + bmax) * 0.5;\n"
    "    vec3 norm = (center - minBound) / extent;\n"
    "\n"
    "    uint morton = morton3D(norm);\n"
    "\n"
    "    b_indices.indices[gid] = gid;\n"
    "    b_mortons.codes[gid] = morton;\n"
    "}\n"
    "";

// Source: bvhBuilder/radixBucket.comp
inline constexpr const char* BVHBUILDER_RADIXBUCKET_COMP =
    "/**\n"
    " * @file radixBucket.comp\n"
    " * @brief Compute shader for computing the base offsets for each bucket in radix sort algorithm.\n"
    " */\n"
    "\n"
    "#version 450\n"
    "\n"
    "layout(local_size_x = 64) in;\n"
    "\n"
    "/**\n"
    " * @brief Uniform buffer containing global information for BVH construction.\n"
    " */\n"
    "layout(binding = 0) uniform BvhGlobal {\n"
    "    uint nElements; // Total number of elements\n"
    "} u_bvhGlobal; // BVH global information buffer\n"
    "\n"
    "/**\n"
    " * @brief Uniform buffer containing information about the current radix pass.\n"
    " */\n"
    "layout(binding = 4) uniform RadixInfo {\n"
    "    uint shift; // Number of bits to shift for the current radix pass\n"
    "} u_radixInfo; // Radix information buffer\n"
    "\n"
    "/**\n"
    " * @brief Storage buffer for storing the histogram bins.\n"
    " */\n"
    "layout(binding = 9) buffer Histogram {\n"
    "    uint bins[]; // Array of histogram bins\n"
    "} b_histogram; // Histogram buffer\n"
    "\n"
    "/**\n"
    " * @brief Storage buffer for storing the base offsets for each bucket in the histogram.\n"
    " */\n"
    "layout(binding = 10) buffer BucketBase {\n"
    "    uint base[64]; // Array of base offsets for each bucket\n"
    "} b_bucketBase; // Bucket base buffer\n"
    "\n"
    "shared uint s_sum[64]; // Shared array for storing the sum of histogram bins for each bucket.\n"
    "\n"
    "void main() {\n"
    "    uint lid = gl_LocalInvocationID.x;\n"
    "    uint nBlocks = (u_bvhGlobal.nElements + 255) / 256;\n"
    "\n"
    "    // Each thread computes the sum of the histogram bins for its corresponding bucket.\n"
    "    uint sum = 0;\n"
    "    for (uint block = 0; block < nBlocks; ++block)\n"
    "        sum += b_histogram.bins[block * 64 + lid];\n"
    "    s_sum[lid] = sum;\n"
    "    barrier();\n"
    "\n"
    "    // The first thread computes the prefix sum (exclusive scan) of the histogram bins\n"
    "    // to determine the base offset for each bucket.\n"
    "    uint prefix = 0;\n"
    "    for (uint i = 0; i < lid; ++i)\n"
    "        prefix += s_sum[i];\n"
    "    b_bucketBase.base[lid] = prefix;\n"
    "}\n"
    "";

// Source: bvhBuilder/radixHist.comp
inline constexpr const char* BVHBUILDER_RADIXHIST_COMP =
    "/**\n"
    " * @file radixHist.comp\n"
    " * @brief Compute shader for building the histogram of Morton codes.\n"
    " */\n"
    "\n"
    "#version 450\n"
    "\n"
    "layout(local_size_x = 256) in;\n"
    "\n"
    "/**\n"
    " * @brief Uniform buffer containing global information for BVH construction.\n"
    " */\n"
    "layout(binding = 0) uniform BvhGlobal {\n"
    "    uint nElements; // Total number of elements\n"
    "} u_bvhGlobal; // BVH global information buffer\n"
    "\n"
    "/**\n"
    " * @brief Uniform buffer containing information about the current radix pass.\n"
    " */\n"
    "layout(binding = 4) uniform RadixInfo {\n"
    "    uint shift; // Number of bits to shift for the current radix pass\n"
    "} u_radixInfo; // Radix information buffer\n"
    "\n"
    "/**\n"
    " * @brief Storage buffer for storing the input Morton codes for each triangle.\n"
    " */\n"
    "layout(binding = 6) readonly buffer MortonsIn {\n"
    "    uint codes[]; // Array of Morton codes corresponding to the triangle indices\n"
    "} b_mortonsIn; // Morton codes input buffer\n"
    "\n"
    "/**\n"
    " * @brief Storage buffer for storing the histogram bins.\n"
    " */\n"
    "layout(binding = 9) buffer Histogram {\n"
    "    uint bins[]; // Array of histogram bins\n"
    "} b_histogram; // Histogram buffer\n"
    "\n"
    "shared uint s_localHist[64]; // Shared array for storing the local histogram for each workgroup\n"
    "\n"
    "void main() {\n"
    "    uint lid = gl_LocalInvocationID.x;\n"
    "    uint gid = gl_GlobalInvocationID.x;\n"
    "    uint group = gl_WorkGroupID.x;\n"
    "\n"
    "    // Initialize the local histogram bins to zero for the current workgroup.\n"
    "    // Each workgroup will compute a histogram for its portion of the data.\n"
    "    if (lid < 64)\n"
    "        s_localHist[lid] = 0;\n"
    "    barrier();\n"
    "\n"
    "    // Each thread processes one element and updates the local histogram based on the Morton code.\n"
    "    if (gid < u_bvhGlobal.nElements) {\n"
    "        uint key = b_mortonsIn.codes[gid];\n"
    "        uint bucket = (key >> u_radixInfo.shift) & 63;\n"
    "        atomicAdd(s_localHist[bucket], 1);\n"
    "    }\n"
    "    barrier();\n"
    "\n"
    "    // After all threads in the workgroup have updated the local histogram,\n"
    "    // the first 64 threads write the results to the global histogram buffer.\n"
    "    if (lid < 64) {\n"
    "        uint index = group * 64 + lid;\n"
    "        b_histogram.bins[index] = s_localHist[lid];\n"
    "    }\n"
    "}\n"
    "";

// Source: bvhBuilder/radixPrefix.comp
inline constexpr const char* BVHBUILDER_RADIXPREFIX_COMP =
    "/**\n"
    " * @file radixPrefix.comp\n"
    " * @brief Compute shader for performing the prefix sum (exclusive scan) on the histogram bins.\n"
    " */\n"
    "\n"
    "#version 450\n"
    "\n"
    "layout(local_size_x = 64) in;\n"
    "\n"
    "/**\n"
    " * @brief Uniform buffer containing global information for BVH construction.\n"
    " */\n"
    "layout(binding = 0) uniform BvhGlobal {\n"
    "    uint nElements; // Total number of elements\n"
    "} u_bvhGlobal; // BVH global information buffer\n"
    "\n"
    "/**\n"
    " * @brief Uniform buffer containing information about the current radix pass.\n"
    " */\n"
    "layout(binding = 4) uniform RadixInfo {\n"
    "    uint shift; // Number of bits to shift for the current radix pass\n"
    "} u_radixInfo; // Radix information buffer\n"
    "\n"
    "/**\n"
    " * @brief Storage buffer for storing the histogram bins.\n"
    " */\n"
    "layout(binding = 9) buffer Histogram {\n"
    "    uint bins[]; // Array of histogram bins\n"
    "} b_histogram; // Histogram buffer\n"
    "\n"
    "/**\n"
    " * @brief Storage buffer for storing the offsets for each bucket in the histogram.\n"
    " */\n"
    "layout(binding = 11) buffer Offsets {\n"
    "    uint offsets[]; // Array of offsets for each bucket\n"
    "} b_offsets; // Offsets buffer\n"
    "\n"
    "void main() {\n"
    "    uint bucket = gl_LocalInvocationID.x;\n"
    "    uint nBlocks = (u_bvhGlobal.nElements + 255) / 256;\n"
    "\n"
    "    uint sum = 0;\n"
    "    for (uint block = 0; block < nBlocks; ++block) {\n"
    "        uint idx = block * 64 + bucket;\n"
    "        uint hist = b_histogram.bins[idx];\n"
    "        b_offsets.offsets[idx] = sum;\n"
    "        sum += hist;\n"
    "    }\n"
    "}\n"
    "";

// Source: bvhBuilder/radixScatt.comp
inline constexpr const char* BVHBUILDER_RADIXSCATT_COMP =
    "/**\n"
    " * @file radixScatt.comp\n"
    " * @brief Compute shader for scattering Morton codes into buckets based on current radix pass.\n"
    " */\n"
    "\n"
    "#version 450\n"
    "\n"
    "layout(local_size_x = 256) in;\n"
    "\n"
    "/**\n"
    " * @brief Uniform buffer containing global information for BVH construction.\n"
    " */\n"
    "layout(binding = 0) uniform BvhGlobal {\n"
    "    uint nElements; // Total number of elements\n"
    "} u_bvhGlobal; // BVH global information buffer\n"
    "\n"
    "/**\n"
    " * @brief Uniform buffer containing information about the current radix pass.\n"
    " */\n"
    "layout(binding = 4) uniform RadixInfo {\n"
    "    uint shift; // Number of bits to shift for the current radix pass\n"
    "} u_radixInfo; // Radix information buffer\n"
    "\n"
    "/**\n"
    " * @brief Storage buffer for storing the input elements indices.\n"
    " */\n"
    "layout(binding = 5) readonly buffer IndicesIn {\n"
    "    uint indices[]; // Array of elements indices\n"
    "} b_indicesIn; // Elements indices input buffer\n"
    "/**\n"
    " * @brief Storage buffer for storing the input Morton codes for each elements.\n"
    " */\n"
    "layout(binding = 6) readonly buffer MortonsIn {\n"
    "    uint codes[]; // Array of Morton codes corresponding to the elements indices\n"
    "} b_mortonsIn; // Morton codes input buffer\n"
    "/**\n"
    " * @brief Storage buffer for storing the output elements indices after scattering.\n"
    " */\n"
    "layout(binding = 7) buffer IndicesOut {\n"
    "    uint indices[]; // Array of elements indices after scattering\n"
    "} b_indicesOut; // Elements indices output buffer\n"
    "/**\n"
    " * @brief Storage buffer for storing the output Morton codes after scattering.\n"
    " */\n"
    "layout(binding = 8) buffer MortonsOut {\n"
    "    uint codes[]; // Array of Morton codes after scattering\n"
    "} b_mortonsOut; // Morton codes output buffer\n"
    "\n"
    "/**\n"
    " * @brief Storage buffer for storing the histogram bins.\n"
    " */\n"
    "layout(binding = 9) buffer Histogram {\n"
    "    uint bins[]; // Array of histogram bins\n"
    "} b_histogram; // Histogram buffer\n"
    "\n"
    "/**\n"
    " * @brief Storage buffer for storing the base offsets for each bucket in the histogram.\n"
    " */\n"
    "layout(binding = 10) buffer BucketBase {\n"
    "    uint base[64]; // Array of base offsets for each bucket\n"
    "} b_bucketBase; // Bucket base buffer\n"
    "\n"
    "/**\n"
    " * @brief Storage buffer for storing the offsets for each bucket in the histogram.\n"
    " */\n"
    "layout(binding = 11) buffer Offsets {\n"
    "    uint offsets[]; // Array of offsets for each bucket\n"
    "} b_offsets; // Offsets buffer\n"
    "\n"
    "shared uint s_localHist[64]; // Shared array for storing the local histogram\n"
    "shared uint s_blockOffset[64]; // Shared array for storing the block offsets for each bucket\n"
    "shared uint s_offsets[64]; // Shared array for storing the offsets from the global offsets buffer\n"
    "\n"
    "void main() {\n"
    "    uint lid = gl_LocalInvocationID.x;\n"
    "    uint gid = gl_GlobalInvocationID.x;\n"
    "    uint block = gl_WorkGroupID.x;\n"
    "\n"
    "    // The first 64 threads in each workgroup load the histogram bins and offsets\n"
    "    // for their block into shared memory.\n"
    "    if (lid < 64) {\n"
    "        uint idx = block * 64 + lid;\n"
    "        s_localHist[lid] = b_histogram.bins[idx];\n"
    "        s_offsets[lid] = b_offsets.offsets[idx];\n"
    "    }\n"
    "    barrier();\n"
    "\n"
    "    // The first thread in the workgroup computes the block offsets for each bucket\n"
    "    // based on the local histogram.\n"
    "    if (lid == 0) {\n"
    "        uint sum = 0;\n"
    "        for (uint b = 0; b < 64; ++b) {\n"
    "            s_blockOffset[b] = sum;\n"
    "            sum += s_localHist[b];\n"
    "        }\n"
    "    }\n"
    "    barrier();\n"
    "\n"
    "    if (gid >= u_bvhGlobal.nElements)\n"
    "        return;\n"
    "\n"
    "    // Each thread processes one element and scatters it to the correct position\n"
    "    // in the output buffer.\n"
    "    uint idxTri = b_indicesIn.indices[gid];\n"
    "    uint code = b_mortonsIn.codes[gid];\n"
    "\n"
    "    uint bucket = (code >> u_radixInfo.shift) & 63;\n"
    "    uint bucketBase = b_bucketBase.base[bucket];\n"
    "    uint offset = s_offsets[bucket];\n"
    "    uint index = bucketBase + offset + atomicAdd(s_blockOffset[bucket], 1);\n"
    "\n"
    "    b_mortonsOut.codes[index] = code;\n"
    "    b_indicesOut.indices[index] = idxTri;\n"
    "}\n"
    "";

// Source: pathTracer.comp
inline constexpr const char* PATHTRACER_COMP =
    "/**\n"
    " * @file pathTracer.comp\n"
    " * @brief Compute shader for path tracing rendering.\n"
    " */\n"
    "\n"
    "#version 450\n"
    "\n"
    "#ifndef VULKAN\n"
    "#extension GL_ARB_bindless_texture : require\n"
    "#else\n"
    "#extension GL_EXT_nonuniform_qualifier : require\n"
    "#endif\n"
    "\n"
    "layout(local_size_x = 32, local_size_y = 32) in;\n"
    "\n"
    "layout(binding = 0, rgba32f) uniform image2D u_outImg; // Output image\n"
    "\n"
    "/**\n"
    " * @brief Uniform struct representing the scene parameters.\n"
    " */\n"
    "layout(binding = 1) uniform Scene {\n"
    "    int resX; // Resolution in X\n"
    "    int resY; // Resolution in Y\n"
    "    int traceDepth; // Trace depth\n"
    "    int currentSample; // Current sample count\n"
    "} u_scene; // Scene parameters\n"
    "\n"
    "/**\n"
    " * @brief Uniform struct representing the camera parameters.\n"
    " */\n"
    "layout(binding = 2) uniform Camera {\n"
    "    vec4 pos; // Camera position\n"
    "    vec4 dir; // Camera direction\n"
    "    vec4 up; // Camera up vector\n"
    "\n"
    "    float focal; // Focal length\n"
    "    float fov; // Field of view\n"
    "    float focusDist; // Focus distance\n"
    "    float fStop; // F-stop value\n"
    "} u_camera; // Camera parameters\n"
    "\n"
    "#ifdef VULKAN\n"
    "layout(binding = 3) uniform sampler2D u_textures[]; // Array of textures\n"
    "#else\n"
    "layout(binding = 3) buffer Textures {\n"
    "    sampler2D u_textures[]; // Array of textures\n"
    "};\n"
    "#endif\n"
    "\n"
    "/**\n"
    " * @brief Sample a texture at given UV coordinates.\n"
    " * @param index The index of the texture.\n"
    " * @param uv The UV coordinates.\n"
    " * @return The sampled color.\n"
    " */\n"
    "vec4 sampleTexture(uint index, vec2 uv) {\n"
    "#ifdef VULKAN\n"
    "    return texture(u_textures[nonuniformEXT(index)], uv);\n"
    "#else\n"
    "    return texture(sampler2D(u_textures[index]), uv);\n"
    "#endif\n"
    "}\n"
    "\n"
    "/**\n"
    " * @brief Struct representing a vertex in the mesh.\n"
    " */\n"
    "struct Vertex {\n"
    "    vec4 pos; // Position\n"
    "    vec4 normal; // Normal\n"
    "    vec4 tangent; // Tangent\n"
    "    vec2 texCoord; // Texture Coordinate\n"
    "    vec2 padding; // Padding for alignment\n"
    "};\n"
    "/**\n"
    " * @brief Storage buffer containing the vertices of the mesh.\n"
    " */\n"
    "layout(binding = 4) readonly buffer Vertices {\n"
    "    Vertex vertices[]; // Array of vertices\n"
    "} b_vertices; // Vertex buffer\n"
    "\n"
    "/**\n"
    " * @brief Struct representing a triangle in the mesh.\n"
    " */\n"
    "struct Triangle {\n"
    "    uint v0; // Index of vertex 0\n"
    "    uint v1; // Index of vertex 1\n"
    "    uint v2; // Index of vertex 2\n"
    "    uint idxMaterial; // Index of the material\n"
    "};\n"
    "/**\n"
    " * @brief Storage buffer containing the triangles of the mesh.\n"
    " */\n"
    "layout(binding = 5) readonly buffer Triangles {\n"
    "    Triangle triangles[]; // Array of triangles\n"
    "} b_triangles; // Triangle buffer\n"
    "\n"
    "/**\n"
    " * @brief Struct representing a material for a mesh.\n"
    " */\n"
    "struct Material {\n"
    "    int type; // Material type\n"
    "    float roughness; // Roughness\n"
    "    float intensity; // Intensity\n"
    "    float ior; // Index of Refraction\n"
    "\n"
    "    uint flags; // Material flags\n"
    "    uint idxNormalTex; // Index of normal texture\n"
    "    uint idxRoughnessTex; // Index of roughness texture\n"
    "    uint idxIntensityTex; // Index of intensity texture\n"
    "};\n"
    "\n"
    "const int MATERIAL_TYPE_DIFFUSE = 0; // Diffuse material\n"
    "const int MATERIAL_TYPE_SPECULAR = 1; // Specular material\n"
    "const int MATERIAL_TYPE_GLOSSY = 2; // Glossy material\n"
    "const int MATERIAL_TYPE_TRANSLUCENT = 3; // Translucent material\n"
    "\n"
    "const uint MATERIAL_NORMAL_MAP = 1 << 0; // Has normal texture\n"
    "const uint MATERIAL_ROUGHNESS_MAP = 1 << 1; // Has roughness texture\n"
    "const uint MATERIAL_INTENSITY_MAP = 1 << 2; // Has intensity texture\n"
    "\n"
    "/**\n"
    " * @brief Storage buffer containing the materials of the mesh.\n"
    " */\n"
    "layout(binding = 6) readonly buffer Materials {\n"
    "    Material materials[]; // Array of materials\n"
    "} b_materials; // Material buffer\n"
    "\n"
    "/**\n"
    " * @brief Struct representing a BVH node.\n"
    " */\n"
    "struct BvhNode {\n"
    "    uint idx; // Index of this node\n"
    "    uint rChildOffset; // Offset to the right child node\n"
    "    uint idxTriangle; // Index of the triangle (if leaf node)\n"
    "    uint leafFlag; // Flag indicating if this is a leaf node\n"
    "\n"
    "    vec4 aabbMin; // Minimum AABB coordinates\n"
    "    vec4 aabbMax; // Maximum AABB coordinates\n"
    "};\n"
    "/**\n"
    " * @brief Storage buffer containing the BVH nodes.\n"
    " */\n"
    "layout(binding = 7) readonly buffer BVH {\n"
    "    BvhNode bvhNodes[]; // Array of BVH nodes\n"
    "} b_BVH; // BVH buffer\n"
    "\n"
    "const float EPS = 0.00001; // Small epsilon value\n"
    "const float INFINITY = 1e20; // Large value representing infinity\n"
    "const float PI = 3.14159265359; // Value of pi\n"
    "\n"
    "uint g_rngState = 0; // Global RNG state\n"
    "/**\n"
    " * @brief Initialize the RNG state based on pixel coordinates and current sample.\n"
    " * @param pixel The pixel coordinates.\n"
    " * @param currentSample The current sample index.\n"
    " */\n"
    "void initRngState(ivec2 pixel, int currentSample) {\n"
    "    g_rngState = uint(pixel.x * 1973u + pixel.y * 9277u + currentSample * 26699u) | 1u;\n"
    "}\n"
    "/**\n"
    " * @brief Generate a random float in the range [0, 1).\n"
    " * @return A random float.\n"
    " */\n"
    "float rand() {\n"
    "    g_rngState ^= g_rngState << 13;\n"
    "    g_rngState ^= g_rngState >> 17;\n"
    "    g_rngState ^= g_rngState << 5;\n"
    "    return float(g_rngState) * (1.0 / 4294967296.0);\n"
    "}\n"
    "\n"
    "/**\n"
    " * @brief Build an orthonormal basis (u, v) given a normal vector (axis).\n"
    " * @param axis The normal vector.\n"
    " * @param[out] u Output vector for the first tangent.\n"
    " * @param[out] v Output vector for the second tangent.\n"
    " */\n"
    "void buildOrthonormalBasis(vec3 axis, out vec3 u, out vec3 v) {\n"
    "    vec3 tmp = abs(axis.x) < 1.0 - EPS\n"
    "        ? vec3(1.0, 0.0, 0.0)\n"
    "        : vec3(0.0, 1.0, 0.0);\n"
    "    u = normalize(cross(tmp, axis));\n"
    "    v = cross(axis, u);\n"
    "}\n"
    "/**\n"
    " * @brief Sample a direction on a hemisphere around the given axis with a cosine-weighted\n"
    "          distribution.\n"
    " * @param axis The normal vector defining the hemisphere.\n"
    " * @param weight The roughness weight for glossy materials (1.0 for diffuse).\n"
    " * @return A sampled direction vector.\n"
    " */\n"
    "vec3 sampleWeightedHemisphere(vec3 axis, float weight) {\n"
    "    vec3 u, v;\n"
    "    buildOrthonormalBasis(axis, u, v);\n"
    "\n"
    "    float w = rand() * weight;\n"
    "    float theta = rand();\n"
    "\n"
    "    vec3 dir =\n"
    "        w * cos(2.0 * PI * theta) * u +\n"
    "        w * sin(2.0 * PI * theta) * v +\n"
    "        sqrt(1.0 - w * w) * axis;\n"
    "\n"
    "    return normalize(dir);\n"
    "}\n"
    "/**\n"
    " * @brief Sample a direction for glass materials based on the incident direction, normal,\n"
    "          and index of refraction.\n"
    " * @param wi The incident direction.\n"
    " * @param n The surface normal at the point of interaction.\n"
    " * @param[inout] inside A flag indicating if the ray is currently inside the material.\n"
    " * @param ior The index of refraction of the material.\n"
    " * @return A sampled direction vector for reflection or refraction.\n"
    " */\n"
    "vec3 sampleGlass(vec3 wi, vec3 n, inout bool inside, float ior) {\n"
    "    float nc = 1.0;\n"
    "    float ng = ior;\n"
    "\n"
    "    float eta = inside ? ng / nc : nc / ng;\n"
    "\n"
    "    float cosi = abs(dot(wi, n));\n"
    "    float r0 = pow((nc - ng) / (nc + ng), 2.0);\n"
    "    float k = 1.0 - eta * eta * (1.0 - cosi * cosi);\n"
    "\n"
    "    vec3 r = reflect(wi, n);\n"
    "\n"
    "    if (k < 0.0)\n"
    "        return r; // Total internal reflection\n"
    "\n"
    "    float re = r0 + (1.0 - r0) * pow(1.0 - cosi, 2.0);\n"
    "\n"
    "    if (rand() < re)\n"
    "        return r;\n"
    "    else {\n"
    "        inside = !inside;\n"
    "        return normalize(\n"
    "            eta * wi - (eta * dot(n, wi) + sqrt(k)) * n\n"
    "        );\n"
    "    }\n"
    "}\n"
    "/**\n"
    " * @brief Sample a point uniformly on a unit disk.\n"
    " * @return A 2D vector representing the sampled point on the disk.\n"
    " */\n"
    "vec2 sampleDisk() {\n"
    "    float r = sqrt(rand());\n"
    "    float theta = 2.0 * PI * rand();\n"
    "    return vec2(cos(theta), sin(theta)) * r;\n"
    "}\n"
    "\n"
    "/**\n"
    " * @brief Struct representing a ray in 3D space.\n"
    " */\n"
    "struct Ray {\n"
    "    vec3 origin; // Origin of the ray\n"
    "    vec3 direction; // Direction of the ray\n"
    "};\n"
    "\n"
    "/**\n"
    " * @brief Struct representing the result of a ray intersection.\n"
    " */\n"
    "struct HitRecord {\n"
    "    bool hit; // Flag indicating if an intersection occurred\n"
    "    float t; // Distance to intersection\n"
    "    vec3 normal; // Surface normal at intersection\n"
    "    vec3 tangent; // Interpolated tangent at intersection\n"
    "    vec2 texCoord; // Texture coordinates at intersection\n"
    "    uint idxMaterial; // Index of the material at intersection\n"
    "};\n"
    "/**\n"
    " * @brief Function to test ray-triangle intersection.\n"
    " * @param ray The ray to test.\n"
    " * @param tri The triangle to test against.\n"
    " * @return The result of the intersection test.\n"
    " */\n"
    "HitRecord hitTriangle(Ray ray, Triangle tri) {\n"
    "    HitRecord result;\n"
    "    result.t = INFINITY;\n"
    "    result.hit = false;\n"
    "\n"
    "    Vertex v0 = b_vertices.vertices[tri.v0];\n"
    "    Vertex v1 = b_vertices.vertices[tri.v1];\n"
    "    Vertex v2 = b_vertices.vertices[tri.v2];\n"
    "\n"
    "    vec3 p0 = v0.pos.xyz;\n"
    "    vec3 p1 = v1.pos.xyz;\n"
    "    vec3 p2 = v2.pos.xyz;\n"
    "\n"
    "    vec3 e1 = p1 - p0;\n"
    "    vec3 e2 = p2 - p0;\n"
    "\n"
    "    vec3 p = cross(ray.direction, e2);\n"
    "    float det = dot(e1, p);\n"
    "\n"
    "    if (abs(det) < EPS)\n"
    "        return result;\n"
    "\n"
    "    float invDet = 1.0 / det;\n"
    "    vec3 tvec = ray.origin - p0;\n"
    "\n"
    "    float u = dot(tvec, p) * invDet;\n"
    "    if (u < 0.0 || u > 1.0)\n"
    "        return result;\n"
    "\n"
    "    vec3 q = cross(tvec, e1);\n"
    "    float v = dot(ray.direction, q) * invDet;\n"
    "    if (v < 0.0 || (u + v) > 1.0)\n"
    "        return result;\n"
    "\n"
    "    float t = dot(e2, q) * invDet;\n"
    "    if (t < EPS)\n"
    "        return result;\n"
    "\n"
    "    /* ===== Hit confirmed ===== */\n"
    "    result.hit = true;\n"
    "    result.t = t;\n"
    "\n"
    "    float w = 1.0 - u - v;\n"
    "\n"
    "    vec3 n0 = v0.normal.xyz;\n"
    "    vec3 n1 = v1.normal.xyz;\n"
    "    vec3 n2 = v2.normal.xyz;\n"
    "    result.normal = normalize(n0 * w + n1 * u + n2 * v);\n"
    "    if (dot(result.normal, ray.direction) > 0.0f)\n"
    "        result.normal = -result.normal;\n"
    "\n"
    "    vec3 t0v = v0.tangent.xyz;\n"
    "    vec3 t1v = v1.tangent.xyz;\n"
    "    vec3 t2v = v2.tangent.xyz;\n"
    "    vec3 tanInterp = t0v * w + t1v * u + t2v * v;\n"
    "    result.tangent = normalize(tanInterp - result.normal * dot(result.normal, tanInterp));\n"
    "\n"
    "    vec2 uv0 = v0.texCoord;\n"
    "    vec2 uv1 = v1.texCoord;\n"
    "    vec2 uv2 = v2.texCoord;\n"
    "    result.texCoord = uv0 * w + uv1 * u + uv2 * v;\n"
    "\n"
    "    result.idxMaterial = tri.idxMaterial;\n"
    "\n"
    "    return result;\n"
    "}\n"
    "/**\n"
    " * @brief Function to test ray-AABB intersection.\n"
    " * @param ray The ray to test.\n"
    " * @param aabbMin The minimum coordinates of the AABB.\n"
    " * @param aabbMax The maximum coordinates of the AABB.\n"
    " * @return The distance to the intersection or INFINITY if no intersection occurs.\n"
    " */\n"
    "float hitAABB(Ray ray, vec3 aabbMin, vec3 aabbMax) {\n"
    "    vec3 invDir = 1.0 / ray.direction;\n"
    "\n"
    "    vec3 t0 = (aabbMin - ray.origin) * invDir;\n"
    "    vec3 t1 = (aabbMax - ray.origin) * invDir;\n"
    "\n"
    "    vec3 tmin = min(t0, t1);\n"
    "    vec3 tmax = max(t0, t1);\n"
    "\n"
    "    float tNear = max(max(tmin.x, tmin.y), tmin.z);\n"
    "    float tFar  = min(min(tmax.x, tmax.y), tmax.z);\n"
    "\n"
    "    if (tFar < max(tNear, 0.0))\n"
    "        return INFINITY;\n"
    "\n"
    "    return tNear;\n"
    "}\n"
    "/**\n"
    " * @brief Function to traverse the BVH and find the closest intersection.\n"
    " * @param ray The ray to trace.\n"
    " * @return The closest hit record.\n"
    " */\n"
    "HitRecord traverseBVH(Ray ray) {\n"
    "    HitRecord closest;\n"
    "    closest.t = INFINITY;\n"
    "    closest.hit = false;\n"
    "\n"
    "    const int MAX_STACK = 64;\n"
    "    int stack[MAX_STACK];\n"
    "    int stackPtr = 0;\n"
    "\n"
    "    stack[stackPtr++] = 0; // root\n"
    "\n"
    "    while (stackPtr > 0) {\n"
    "        int nodeIdx = stack[--stackPtr];\n"
    "        BvhNode node = b_BVH.bvhNodes[nodeIdx];\n"
    "\n"
    "        float nodeHit = hitAABB(ray, node.aabbMin.xyz, node.aabbMax.xyz);\n"
    "        if (nodeHit == INFINITY || nodeHit > closest.t)\n"
    "            continue;\n"
    "\n"
    "        if (node.leafFlag != 0) {\n"
    "            Triangle tri = b_triangles.triangles[node.idxTriangle];\n"
    "            HitRecord hit = hitTriangle(ray, tri);\n"
    "\n"
    "            if (hit.hit && hit.t < closest.t)\n"
    "                closest = hit;\n"
    "        } else {\n"
    "            int leftChild  = nodeIdx + 1;\n"
    "            int rightChild = int(nodeIdx + node.rChildOffset);\n"
    "\n"
    "            float tLeft = hitAABB(\n"
    "                ray,\n"
    "                b_BVH.bvhNodes[leftChild].aabbMin.xyz,\n"
    "                b_BVH.bvhNodes[leftChild].aabbMax.xyz\n"
    "            );\n"
    "\n"
    "            float tRight = INFINITY;\n"
    "            if (node.rChildOffset != 0) {\n"
    "                tRight = hitAABB(\n"
    "                    ray,\n"
    "                    b_BVH.bvhNodes[rightChild].aabbMin.xyz,\n"
    "                    b_BVH.bvhNodes[rightChild].aabbMax.xyz\n"
    "                );\n"
    "            }\n"
    "\n"
    "            if (tLeft < tRight) {\n"
    "                if (tRight < INFINITY)\n"
    "                    stack[stackPtr++] = rightChild;\n"
    "                if (tLeft < INFINITY)\n"
    "                    stack[stackPtr++] = leftChild;\n"
    "            } else {\n"
    "                if (tLeft < INFINITY)\n"
    "                    stack[stackPtr++] = leftChild;\n"
    "                if (tRight < INFINITY)\n"
    "                    stack[stackPtr++] = rightChild;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    return closest;\n"
    "}\n"
    "\n"
    "/**\n"
    " * @brief Struct to hold polarization information at each interaction.\n"
    " */\n"
    "struct PolarInfo {\n"
    "    vec3 normal; // Interaction normal\n"
    "    vec3 dirOut; // Outgoing direction\n"
    "    vec2 r; // Reflection coefficients (rs, rp)\n"
    "    vec3 s; // Stokes vector\n"
    "};\n"
    "const int MAX_DEPTH = 10; // Maximum trace depth\n"
    "PolarInfo g_polarInfoList[MAX_DEPTH]; // List of polarization info\n"
    "/**\n"
    " * @brief Calculate the Fresnel reflection coefficients for s and p polarizations.\n"
    " * @param n1 Index of refraction of the incident medium.\n"
    " * @param n2 Index of refraction of the transmitted medium.\n"
    " * @param cos_i Cosine of the incident angle.\n"
    " * @return A vec2 containing (rs, rp).\n"
    " */\n"
    "vec2 getRsRp(float n1, float n2, float cos_i) {\n"
    "    cos_i = abs(cos_i);\n"
    "    float cos_t = sqrt(1.0 - (n1 * n1) / (n2 * n2) * (1.0 - cos_i * cos_i));\n"
    "    float rs = (n1 * cos_i - n2 * cos_t) / (n1 * cos_i + n2 * cos_t);\n"
    "    float rp = (n2 * cos_i - n1 * cos_t) / (n1 * cos_t + n2 * cos_i);\n"
    "    return vec2(rs, rp);\n"
    "}\n"
    "/**\n"
    " * @brief Create a rotation matrix for the Stokes vector based on the rotation angle phi.\n"
    " * @param phi The rotation angle in radians.\n"
    " * @return A 3x3 matrix representing the rotation of the Stokes vector.\n"
    " */\n"
    "mat3 stokesRotation(float phi) {\n"
    "    float c = cos(2.0 * phi);\n"
    "    float s = sin(2.0 * phi);\n"
    "    return mat3(\n"
    "        1.0, 0.0, 0.0,\n"
    "        0.0, c,   -s,\n"
    "        0.0, s,   c\n"
    "    );\n"
    "}\n"
    "/**\n"
    " * @brief Calculate the final Stokes vector result based on the ray direction and trace depth.\n"
    " * @param rayDir The direction of the ray.\n"
    " * @param depth The trace depth.\n"
    " * @return The final Stokes vector representing the polarization state.\n"
    " */\n"
    "vec3 calcPolarResult(vec3 rayDir, int depth) {\n"
    "    // Stokes vector: (S0, S1, S2)\n"
    "    vec3 S = vec3(0.0);\n"
    "\n"
    "    if (depth <= 0)\n"
    "        return S;\n"
    "\n"
    "    vec3 s = normalize(vec3(rand() * 2.0 - 1.0, rand() * 2.0 - 1.0, rand() * 2.0 - 1.0));\n"
    "    float phi = 2.0 * PI;\n"
    "\n"
    "    for (int i = depth - 1; i >= 0; --i) {\n"
    "        PolarInfo info = g_polarInfoList[i];\n"
    "\n"
    "        vec3 d = info.dirOut;\n"
    "        vec3 s_old = s;\n"
    "\n"
    "        s = normalize(cross(info.normal, d));\n"
    "        \n"
    "        float cosPhi = clamp(dot(s, s_old), -1.0, 1.0);\n"
    "        phi = acos(cosPhi) * sign(dot(cross(s_old, s), d));\n"
    "\n"
    "        S = stokesRotation(phi) * S;\n"
    "\n"
    "        float rs = info.r.x;\n"
    "        float rp = info.r.y;\n"
    "        float Rs = rs * rs;\n"
    "        float Rp = rp * rp;\n"
    "\n"
    "        mat3 refl = mat3(\n"
    "            vec3((Rs + Rp) / 2.0, (Rs - Rp) / 2.0, 0.0),\n"
    "            vec3((Rs - Rp) / 2.0, (Rs + Rp) / 2.0, 0.0),\n"
    "            vec3(0.0, 0.0, rs * rp)\n"
    "        );\n"
    "\n"
    "        mat3 trans = mat3(\n"
    "            vec3(1.0 - (Rs + Rp) / 2.0, (Rp - Rs) / 2.0, 0.0),\n"
    "            vec3((Rp - Rs) / 2.0, 1.0 - (Rs + Rp) / 2.0, 0.0),\n"
    "            vec3(0.0, 0.0, sqrt((1.0 - Rs) * (1.0 - Rp)))\n"
    "        );\n"
    "\n"
    "        S = refl * S + trans * info.s;\n"
    "    }\n"
    "\n"
    "    vec3 s_cam = normalize(cross(vec3(0.0, 0.0, 1.0), normalize(rayDir)));\n"
    "    float cosPhi = clamp(dot(s_cam, s), -1.0, 1.0);\n"
    "    phi = acos(cosPhi) * sign(dot(cross(s, s_cam), normalize(rayDir)));\n"
    "\n"
    "    return stokesRotation(phi) * S;\n"
    "}\n"
    "\n"
    "/**\n"
    " * @brief Trace a ray through the scene and calculate the resulting color and polarization.\n"
    " * @param ray The ray to trace.\n"
    " * @return A vec4 containing the RGB color and depth (R, G, B, Depth).\n"
    " */\n"
    "vec4 trace(Ray ray) {\n"
    "    Ray newRay = ray;\n"
    "    int bounces = 0;\n"
    "    bool inside = false;\n"
    "    float sceneDepth = 0.0;\n"
    "\n"
    "    while (bounces < u_scene.traceDepth) {\n"
    "        HitRecord hit = traverseBVH(newRay);\n"
    "        if (hit.hit) {\n"
    "            if (bounces == 0)\n"
    "                sceneDepth = hit.t;\n"
    "\n"
    "            vec3 p = newRay.origin + newRay.direction * hit.t;\n"
    "            vec3 n = hit.normal;\n"
    "            Material material = b_materials.materials[hit.idxMaterial];\n"
    "            if ((material.flags & MATERIAL_NORMAL_MAP) != 0) {\n"
    "                vec3 t = hit.tangent;\n"
    "                vec3 b = normalize(cross(n, t));\n"
    "                mat3 TBN = mat3(t, b, n);\n"
    "                vec3 nTex =\n"
    "                    sampleTexture(material.idxNormalTex, hit.texCoord).xyz * 2.0 - 1.0;\n"
    "                n = normalize(TBN * nTex);\n"
    "            }\n"
    "            p += n + EPS;\n"
    "\n"
    "            vec3 wi = newRay.direction;\n"
    "            vec3 wo = reflect(wi, n);\n"
    "\n"
    "            // Material sampling\n"
    "            if (material.type == MATERIAL_TYPE_DIFFUSE)\n"
    "                wo = sampleWeightedHemisphere(n, 1.0);\n"
    "            else if (material.type == MATERIAL_TYPE_GLOSSY) {\n"
    "                float roughness = material.roughness;\n"
    "                if ((material.flags & MATERIAL_ROUGHNESS_MAP) != 0)\n"
    "                    roughness = sampleTexture(material.idxRoughnessTex, hit.texCoord).r;\n"
    "                vec3 r = reflect(wi, n);\n"
    "                wo = sampleWeightedHemisphere(r, roughness);\n"
    "            }\n"
    "            else if (material.type == MATERIAL_TYPE_TRANSLUCENT) {\n"
    "                wo = sampleGlass(wi, n, inside, material.ior);\n"
    "                if (inside)\n"
    "                    p -= n * EPS * 2.0;\n"
    "            }\n"
    "\n"
    "            // Polarization bookkeeping\n"
    "            PolarInfo info;\n"
    "            info.dirOut = wo;\n"
    "            vec3 normal = normalize(wo - wi);\n"
    "            if (abs(1.0 - dot(wo, wi)) < EPS)\n"
    "                normal = n;\n"
    "            info.normal = normal;\n"
    "            info.r = getRsRp(1.0, material.ior, dot(info.normal, wi));\n"
    "            float theta = 2.0 * PI * rand();\n"
    "            float intensity = material.intensity;\n"
    "            if ((material.flags & MATERIAL_INTENSITY_MAP) != 0)\n"
    "                intensity = sampleTexture(material.idxIntensityTex, hit.texCoord).r;\n"
    "            info.s = vec3(1.0, cos(theta), sin(theta)) * intensity;\n"
    "            g_polarInfoList[bounces] = info;\n"
    "\n"
    "            // Next ray\n"
    "            newRay.origin = p;\n"
    "            newRay.direction = wo;\n"
    "            bounces++;\n"
    "        } else\n"
    "            break;\n"
    "    }\n"
    "\n"
    "    return vec4(calcPolarResult(ray.direction, bounces), sceneDepth);\n"
    "}\n"
    "\n"
    "void main() {\n"
    "    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);\n"
    "\n"
    "    if (pixel.x >= u_scene.resX || pixel.y >= u_scene.resY)\n"
    "        return;\n"
    "\n"
    "    initRngState(pixel, u_scene.currentSample);\n"
    "\n"
    "    vec2 uv = (vec2(pixel) + 0.5) / vec2(u_scene.resX, u_scene.resY);\n"
    "    vec2 ndc = uv * 2.0 - 1.0;\n"
    "\n"
    "    vec3 forward = normalize(u_camera.dir.xyz);\n"
    "    vec3 right = normalize(cross(forward, u_camera.up.xyz));\n"
    "    vec3 up = cross(right, forward);\n"
    "\n"
    "    float halfHeight = tan(radians(u_camera.fov * 0.5)) * u_camera.focal;\n"
    "    float halfWidth  = halfHeight * float(u_scene.resX) / float(u_scene.resY);\n"
    "\n"
    "    vec3 imageCenter = u_camera.pos.xyz + forward * u_camera.focal;\n"
    "    vec3 imagePoint = imageCenter + ndc.x * halfWidth * right + ndc.y * halfHeight * up;\n"
    "\n"
    "    vec3 pinholeDir = normalize(imagePoint - u_camera.pos.xyz);\n"
    "    // Focus plane intersection\n"
    "    float tFocus = u_camera.focusDist / dot(pinholeDir, forward);\n"
    "    vec3 focusPoint = u_camera.pos.xyz + pinholeDir * tFocus;\n"
    "    // Aperture\n"
    "    float apertureRadius = 0.5 * (u_camera.focal / u_camera.fStop);\n"
    "    // Lens sampling\n"
    "    vec2 lensSample = sampleDisk() * apertureRadius;\n"
    "    vec3 lensOffset = right * lensSample.x + up * lensSample.y;\n"
    "\n"
    "    Ray ray;\n"
    "    ray.origin = u_camera.pos.xyz + lensOffset;\n"
    "    ray.direction = normalize(focusPoint - ray.origin);\n"
    "    vec4 color = trace(ray);\n"
    "\n"
    "    if (u_scene.currentSample > 1)\n"
    "        color += imageLoad(u_outImg, pixel) * (u_scene.currentSample - 1);\n"
    "    imageStore(u_outImg, pixel, vec4(color / float(u_scene.currentSample)));\n"
    "}\n"
    "";

// Source: preview.frag
inline constexpr const char* PREVIEW_FRAG =
    "/**\n"
    " * @file preview.frag\n"
    " * @brief Fragment shader for the previewer.\n"
    " */\n"
    "\n"
    "#version 450\n"
    "\n"
    "layout(location = 0) in vec3 v_posW; // World space position\n"
    "layout(location = 1) in vec3 v_normalW; // World space normal\n"
    "layout(location = 2) in vec3 v_tangentW; // World space tangent\n"
    "layout(location = 3) in vec2 v_texCoord; // Texture coordinate\n"
    "\n"
    "/**\n"
    " * @brief Uniform struct for camera position.\n"
    " */\n"
    "#ifdef VULKAN\n"
    "layout(set = 2, binding = 1)\n"
    "#else\n"
    "layout(binding = 1)\n"
    "#endif\n"
    "uniform Camera {\n"
    "    vec3 posW; // Camera world position\n"
    "} u_camera; // Camera data\n"
    "\n"
    "/**\n"
    " * @brief Uniform struct for material properties.\n"
    " */\n"
    "layout(binding = 2) uniform Material {\n"
    "    vec4 diffuse; // Diffuse color (or highlight color)\n"
    "    float roughness; // Roughness\n"
    "    uint flags; // Material flags\n"
    "} u_material; // Material data\n"
    "const uint MATERIAL_NORMAL_MAP = 1 << 0; // Has normal texture\n"
    "const uint MATERIAL_ROUGHNESS_MAP = 1 << 1; // Has roughness texture\n"
    "const uint MATERIAL_INTENSITY_MAP = 1 << 2; // Has intensity texture (not used)\n"
    "const uint MATERIAL_HIGHLIGHT = 1 << 3; // Highlighted material\n"
    "\n"
    "layout(binding = 3) uniform sampler2D u_normalTex; // Normal texture\n"
    "layout(binding = 4) uniform sampler2D u_roughnessTex; // Roughness texture\n"
    "layout(binding = 5) uniform sampler2D u_intensityTex; // Intensity texture\n"
    "\n"
    "/**\n"
    " * @brief Uniform struct for object picking information.\n"
    " */\n"
    "layout(binding = 6) uniform PickInfo {\n"
    "    uint modelID; // Model ID\n"
    "    uint meshID; // Mesh ID\n"
    "} u_pickInfo; // Picking information\n"
    "\n"
    "layout(location = 0) out vec4 o_fragColor; // Final fragment color\n"
    "layout(location = 1) out vec4 o_pickColor; // Picking color for color pick buffer\n"
    "\n"
    "void main() {\n"
    "    // Light direction in world space (camera as light source)\n"
    "    vec3 l = normalize(u_camera.posW - v_posW);\n"
    "    // Normal in world space\n"
    "    vec3 n = normalize(v_normalW);\n"
    "    if (dot(n, l) < 0.0)\n"
    "        n = -n;\n"
    "    if ((u_material.flags & MATERIAL_NORMAL_MAP) != 0) {\n"
    "        vec3 bitangentW = normalize(cross(v_normalW, v_tangentW));\n"
    "        mat3 tbn = mat3(v_tangentW, bitangentW, v_normalW);\n"
    "        vec3 nt = normalize(texture(u_normalTex, v_texCoord).xyz * 2.0 - 1.0);\n"
    "        n = tbn * nt;\n"
    "    }\n"
    "\n"
    "    float roughness = u_material.roughness;\n"
    "    if ((u_material.flags & MATERIAL_ROUGHNESS_MAP) != 0)\n"
    "        roughness = texture(u_roughnessTex, v_texCoord).r;\n"
    "\n"
    "    vec3 diffuse = u_material.diffuse.rgb;\n"
    "    if ((u_material.flags & MATERIAL_INTENSITY_MAP) != 0)\n"
    "        diffuse = texture(u_intensityTex, v_texCoord).rgb;\n"
    "    diffuse *= max(dot(n, l), 0.0);\n"
    "\n"
    "    vec3 specular = vec3(1.0);\n"
    "    float specularFact = pow(max(dot(n, l), 0.0), 128.0 * (1.0 - roughness));\n"
    "    specularFact *= max(dot(n, l), 0.0);\n"
    "    specular *= specularFact;\n"
    "\n"
    "    vec3 shade = (diffuse + specular) * 0.5;\n"
    "    if ((u_material.flags & MATERIAL_HIGHLIGHT) != 0)\n"
    "        shade = diffuse;\n"
    "\n"
    "    o_fragColor = vec4(shade, 1.0);\n"
    "\n"
    "    o_pickColor = vec4(u_pickInfo.modelID, u_pickInfo.meshID, 1.0, 1.0);\n"
    "}\n"
    "";

// Source: preview.vert
inline constexpr const char* PREVIEW_VERT =
    "/**\n"
    " * @file preview.vert\n"
    " * @brief Vertex shader for the previewer.\n"
    " */\n"
    "\n"
    "#version 450\n"
    "\n"
    "layout(location = 0) in vec3 i_pos; // Vertex position\n"
    "layout(location = 1) in vec3 i_normal; // Vertex normal\n"
    "layout(location = 2) in vec3 i_tangent; // Vertex tangent\n"
    "layout(location = 3) in vec2 i_texCoord; // Vertex texture coordinate\n"
    "\n"
    "/**\n"
    " * @brief Uniform struct for model, view, and projection matrices.\n"
    " */\n"
    " #ifdef VULKAN\n"
    "layout(set = 1, binding = 0)\n"
    "#else\n"
    "layout(binding = 0)\n"
    "#endif\n"
    "uniform Xform {\n"
    "    mat4 proj; // Projection matrix\n"
    "    mat4 view; // View matrix\n"
    "    mat4 model; // Model matrix\n"
    "} u_xform; // Transformation matrices\n"
    "\n"
    "layout(location = 0) out vec3 v_posW; // World space position\n"
    "layout(location = 1) out vec3 v_normalW; // World space normal\n"
    "layout(location = 2) out vec3 v_tangentW; // World space tangent\n"
    "layout(location = 3) out vec2 v_texCoord; // Texture coordinate\n"
    "\n"
    "void main() {\n"
    "    v_posW = vec3(u_xform.model * vec4(i_pos, 1.0));\n"
    "    v_normalW = normalize(mat3(u_xform.model) * i_normal);\n"
    "    v_tangentW = normalize(mat3(u_xform.model) * i_tangent);\n"
    "    v_texCoord = i_texCoord;\n"
    "\n"
    "    gl_Position = u_xform.proj * u_xform.view * vec4(v_posW, 1.0);\n"
    "}\n"
    "";

// Source: quad.frag
inline constexpr const char* QUAD_FRAG =
    "/**\n"
    " * @file quad.frag\n"
    " * @brief Fragment shader for rendering a textured quad.\n"
    " */\n"
    "\n"
    "#version 450\n"
    "\n"
    "layout(location = 0) in vec2 v_texCoord; // Texture coordinate\n"
    "\n"
    "layout(binding = 0) uniform sampler2D u_texture; // Texture sampler\n"
    "\n"
    "/**\n"
    " * @brief Uniform buffer for shader parameters.\n"
    " */\n"
    "layout(binding = 1) uniform Params {\n"
    "    int channel; // Channel selection (0 for red, 1 for green, 2 for blue)\n"
    "} u_params; // Shader parameters\n"
    "\n"
    "layout(location = 0) out vec4 o_fragColor; // Final fragment color\n"
    "\n"
    "void main() {\n"
    "    vec3 color = texture(u_texture, v_texCoord).rgb;\n"
    "    o_fragColor = vec4(0.0, 0.0, 0.0, 1.0);\n"
    "    if (u_params.channel == 0) {\n"
    "        color *= 5.0;\n"
    "        o_fragColor = vec4(color.rrr, 1.0);\n"
    "    } else {\n"
    "        color = 1.0 - (color + 0.025) * 20.0;\n"
    "        if (u_params.channel == 1)\n"
    "            o_fragColor = vec4(color.ggg, 1.0);\n"
    "        else if (u_params.channel == 2)\n"
    "            o_fragColor = vec4(color.bbb, 1.0);\n"
    "    }\n"
    "}\n"
    "";

// Source: quad.vert
inline constexpr const char* QUAD_VERT =
    "/**\n"
    " * @file quad.vert\n"
    " * @brief Vertex shader for rendering a textured quad.\n"
    " */\n"
    "\n"
    "#version 450\n"
    "\n"
    "#ifdef VULKAN\n"
    "#define gl_VertexID gl_VertexIndex\n"
    "#endif\n"
    "\n"
    "layout(location = 0) out vec2 v_texCoord; // Output texture coordinates\n"
    "\n"
    "// Predefined vertex positions for a full-screen quad\n"
    "const vec4 g_vertices[4] = vec4[](\n"
    "    vec4(-1.0, -1.0, 0.0, 1.0),\n"
    "    vec4( 1.0, -1.0, 0.0, 1.0),\n"
    "    vec4(-1.0,  1.0, 0.0, 1.0),\n"
    "    vec4( 1.0,  1.0, 0.0, 1.0)\n"
    ");\n"
    "\n"
    "void main() {\n"
    "    gl_Position = g_vertices[gl_VertexID];\n"
    "    v_texCoord = (gl_Position.xy + vec2(1.0)) * 0.5;\n"
    "}\n"
    "";

/**
 * @brief Retrieve the shader string by name.
 * @param name The name of the shader file.
 * @return The shader source code as a string, or an empty string if not found.
 */
inline std::string get(const std::string& name) {
    static const auto map = std::unordered_map<std::string, std::string> {
        { "bvhBuilder/bound.comp", BVHBUILDER_BOUND_COMP },
        { "bvhBuilder/bvhAABB.comp", BVHBUILDER_BVHAABB_COMP },
        { "bvhBuilder/bvhInternal.comp", BVHBUILDER_BVHINTERNAL_COMP },
        { "bvhBuilder/bvhLeafBLAS.comp", BVHBUILDER_BVHLEAFBLAS_COMP },
        { "bvhBuilder/bvhLeafTLAS.comp", BVHBUILDER_BVHLEAFTLAS_COMP },
        { "bvhBuilder/mortonBLAS.comp", BVHBUILDER_MORTONBLAS_COMP },
        { "bvhBuilder/mortonTLAS.comp", BVHBUILDER_MORTONTLAS_COMP },
        { "bvhBuilder/radixBucket.comp", BVHBUILDER_RADIXBUCKET_COMP },
        { "bvhBuilder/radixHist.comp", BVHBUILDER_RADIXHIST_COMP },
        { "bvhBuilder/radixPrefix.comp", BVHBUILDER_RADIXPREFIX_COMP },
        { "bvhBuilder/radixScatt.comp", BVHBUILDER_RADIXSCATT_COMP },
        { "pathTracer.comp", PATHTRACER_COMP },
        { "preview.frag", PREVIEW_FRAG },
        { "preview.vert", PREVIEW_VERT },
        { "quad.frag", QUAD_FRAG },
        { "quad.vert", QUAD_VERT },
    };
    if (auto it = map.find(name); it != map.end())
        return it->second;
    return {};
}

} // namespace ShaderStrings
