/**
 * @file bvhLeafBLAS.comp
 * @brief Compute shader for constructing the leaf nodes of a BVH tree.
 */

#version 450

layout(local_size_x = 256) in;

/**
 * @brief Uniform buffer containing global information for BVH construction.
 */
layout(binding = 0) uniform BvhGlobal {
    uint nElements; // Total number of elements
} u_bvhGlobal; // BVH global information buffer

/**
 * @brief Struct representing a vertex in the mesh.
 */
struct Vertex {
    vec4 pos; // Position
    vec4 normal; // Normal
    vec4 tangent; // Tangent
    vec2 texCoord; // Texture Coordinate
    vec2 padding; // Padding for alignment
};
/**
 * @brief Storage buffer containing the vertices of the mesh.
 */
layout(binding = 1) readonly buffer Vertices {
    Vertex vertices[]; // Array of vertices
} b_vertices; // Vertex buffer

/**
 * @brief Struct representing a triangle in the mesh.
 */
struct Triangle {
    uint v0; // Index of vertex 0
    uint v1; // Index of vertex 1
    uint v2; // Index of vertex 2
    uint idxMaterial; // Index of the material
};
/**
 * @brief Storage buffer containing the triangles of the mesh.
 */
layout(binding = 2) readonly buffer Triangles {
    Triangle triangles[]; // Array of triangles
} b_triangles; // Triangle buffer

/**
 * @brief Storage buffer for storing the input elements indices.
 */
layout(binding = 7) readonly buffer IndicesIn {
    uint indices[]; // Array of elements indices
} b_indicesIn; // Elements indices input buffer

/**
 * @brief Struct representing a node in the BVH tree.
 */
struct BvhNode {
    int idxLeft; // Index of the left child node
    int idxRight; // Index of the right child node
    int idxParent; // Index of the parent node
    int idxTriangle; // Index of the triangle for leaf nodes

    vec4 aabbMin; // Minimum corner of the axis-aligned bounding box (AABB) for the node
    vec4 aabbMax; // Maximum corner of the axis-aligned bounding box (AABB) for the node
};
/**
 * @brief Storage buffer for storing the BVH nodes of the tree.
 */
layout(binding = 13) buffer BvhNodes {
    BvhNode nodes[]; // Array of BVH nodes representing the internal structure of the BVH tree
} b_bvhNodes; // BVH nodes buffer

void main() {
    uint i = gl_GlobalInvocationID.x;
    uint N = u_bvhGlobal.nElements;

    if (i >= N)
        return;

    uint idx = b_indicesIn.indices[i];
    Triangle tri = b_triangles.triangles[idx];

    vec3 v0 = b_vertices.vertices[tri.v0].pos.xyz;
    vec3 v1 = b_vertices.vertices[tri.v1].pos.xyz;
    vec3 v2 = b_vertices.vertices[tri.v2].pos.xyz;

    vec3 bmin = min(v0, min(v1, v2));
    vec3 bmax = max(v0, max(v1, v2));

    uint leafIdx = i + (N - 1);

    b_bvhNodes.nodes[leafIdx].idxLeft = -1;
    b_bvhNodes.nodes[leafIdx].idxRight = -1;
    b_bvhNodes.nodes[leafIdx].idxTriangle = int(idx);

    b_bvhNodes.nodes[leafIdx].aabbMin = vec4(bmin, 0.0);
    b_bvhNodes.nodes[leafIdx].aabbMax = vec4(bmax, 0.0);
}
