/**
 * @file mortonBLAS.comp
 * @brief Compute shader for calculating Morton codes for triangles in a model.
 */

#version 450

layout(local_size_x = 128) in;

/**
 * @brief Uniform buffer containing global information for BVH construction.
 */
layout(binding = 0) uniform BvhGlobal {
    uint nElements; // Total number of elements
} u_bvhGlobal; // BVH global information buffer

/**
 * @brief Struct representing a vertex in the mesh.
 */
struct Vertex {
    vec4 pos; // Position
    vec4 normal; // Normal
    vec4 tangent; // Tangent
    vec2 texCoord; // Texture Coordinate
    vec2 padding; // Padding for alignment
};
/**
 * @brief Storage buffer containing the vertices of the mesh.
 */
layout(binding = 1) readonly buffer Vertices {
    Vertex vertices[]; // Array of vertices
} b_vertices; // Vertex buffer

/**
 * @brief Struct representing a triangle in the mesh.
 */
struct Triangle {
    uint v0; // Index of vertex 0
    uint v1; // Index of vertex 1
    uint v2; // Index of vertex 2
    uint idxMaterial; // Index of the material
};
/**
 * @brief Storage buffer containing the triangles of the mesh.
 */
layout(binding = 2) readonly buffer Triangles {
    Triangle triangles[]; // Array of triangles
} b_triangles; // Triangle buffer

/**
 * @brief Uniform buffer for storing the axis-aligned bounding box (AABB) of the model.
 */
layout(binding = 3) readonly buffer Bounds {
    vec4 minBound; // Minimum bound of the AABB
    vec4 maxBound; // Maximum bound of the AABB
} u_bounds; // Bounds buffer

/**
 * @brief Storage buffer for storing the output element indices after computing Morton codes.
 */
layout(binding = 5) writeonly buffer Indices {
    uint indices[]; // Array of element indices corresponding to the Morton codes
} b_indices; // Element indices buffer
/**
 * @brief Storage buffer for storing the computed Morton codes for each triangle.
 */
layout(binding = 6) writeonly buffer Mortons {
    uint codes[]; // Array of Morton codes corresponding to the triangle indices
} b_mortons; // Morton codes buffer

const float EPS = 0.00001; // Small epsilon value

/**
 * @brief Expands a 10-bit integer into a 30-bit integer by inserting two zeros between each bit.
 *
 * This function takes a 10-bit integer and expands it to a 30-bit integer by interleaving zeros
 * between the bits. This is used for computing Morton codes for spatial indexing.
 *
 * @param v The input 10-bit integer to be expanded.
 * @return The expanded 30-bit integer with interleaved zeros.
 */
uint expandBits(uint v) {
    v = (v * 0x00010001u) & 0xFF0000FFu;
    v = (v * 0x00000101u) & 0x0F00F00Fu;
    v = (v * 0x00000011u) & 0xC30C30C3u;
    v = (v * 0x00000005u) & 0x49249249u;
    return v;
}

/**
 * @brief Computes the 30-bit Morton code for a 3D point normalized to the unit cube.
 *
 * This function takes a 3D point with coordinates in the range [0, 1] and computes its Morton code
 * by expanding each coordinate into a 10-bit integer and interleaving the bits. The resulting
 * Morton code is a 30-bit integer that can be used for spatial indexing.
 *
 * @param v The input 3D point with coordinates in the range [0, 1].
 * @return The computed 30-bit Morton code for the input point.
 */
uint morton3D(vec3 v) {
    v = clamp(v * 1024.0, 0.0, 1023.0);

    uint xx = expandBits(uint(v.x));
    uint yy = expandBits(uint(v.y));
    uint zz = expandBits(uint(v.z));

    return (xx << 2) | (yy << 1) | zz;
}

void main() {
    uint gid = gl_GlobalInvocationID.x;
    if (gid >= u_bvhGlobal.nElements)
        return;

    Triangle tri = b_triangles.triangles[gid];

    vec3 v0 = b_vertices.vertices[tri.v0].pos.xyz;
    vec3 v1 = b_vertices.vertices[tri.v1].pos.xyz;
    vec3 v2 = b_vertices.vertices[tri.v2].pos.xyz;

    vec3 minBound = u_bounds.minBound.xyz;
    vec3 maxBound = u_bounds.maxBound.xyz;

    vec3 extent = maxBound - minBound;
    extent = max(extent, vec3(EPS)); // Avoid division by zero
    vec3 center = (v0 + v1 + v2) * (1.0 / 3.0);
    vec3 norm = (center - minBound) / extent;

    uint morton = morton3D(norm);

    b_indices.indices[gid] = gid;
    b_mortons.codes[gid] = morton;
}
