/**
 * @file radixHist.comp
 * @brief Compute shader for building the histogram of Morton codes.
 */

#version 450

layout(local_size_x = 256) in;

/**
 * @brief Uniform buffer containing global information for BVH construction.
 */
layout(binding = 0) uniform BvhGlobal {
    uint nElements; // Total number of elements
} u_bvhGlobal; // BVH global information buffer

/**
 * @brief Uniform buffer containing information about the current radix pass.
 */
layout(binding = 4) uniform RadixInfo {
    uint shift; // Number of bits to shift for the current radix pass
} u_radixInfo; // Radix information buffer

/**
 * @brief Storage buffer for storing the input Morton codes for each triangle.
 */
layout(binding = 6) readonly buffer MortonsIn {
    uint codes[]; // Array of Morton codes corresponding to the triangle indices
} b_mortonsIn; // Morton codes input buffer

/**
 * @brief Storage buffer for storing the histogram bins.
 */
layout(binding = 9) buffer Histogram {
    uint bins[]; // Array of histogram bins
} b_histogram; // Histogram buffer

shared uint s_localHist[64]; // Shared array for storing the local histogram for each workgroup

void main() {
    uint lid = gl_LocalInvocationID.x;
    uint gid = gl_GlobalInvocationID.x;
    uint group = gl_WorkGroupID.x;

    // Initialize the local histogram bins to zero for the current workgroup.
    // Each workgroup will compute a histogram for its portion of the data.
    if (lid < 64)
        s_localHist[lid] = 0;
    barrier();

    // Each thread processes one element and updates the local histogram based on the Morton code.
    if (gid < u_bvhGlobal.nElements) {
        uint key = b_mortonsIn.codes[gid];
        uint bucket = (key >> u_radixInfo.shift) & 63;
        atomicAdd(s_localHist[bucket], 1);
    }
    barrier();

    // After all threads in the workgroup have updated the local histogram,
    // the first 64 threads write the results to the global histogram buffer.
    if (lid < 64) {
        uint index = group * 64 + lid;
        b_histogram.bins[index] = s_localHist[lid];
    }
}
